package codegen

import (
	"strings"
	"testing"

	"github.com/dylanblakemore/golem/internal/ast"
	"github.com/dylanblakemore/golem/internal/desugar"
	"github.com/dylanblakemore/golem/internal/golifter"
	"github.com/dylanblakemore/golem/internal/goloader"
	"github.com/dylanblakemore/golem/internal/lexer"
	"github.com/dylanblakemore/golem/internal/parser"
	"github.com/dylanblakemore/golem/internal/resolver"
)

// generate runs the full pipeline: lex -> parse -> resolve -> desugar -> generate.
func generate(t *testing.T, source string) string {
	t.Helper()
	l := lexer.New(source, "test.golem")
	tokens := l.Tokenize()
	p := parser.New(tokens, "test.golem")
	mod, perrs := p.Parse()
	if len(perrs) > 0 {
		t.Fatalf("parse errors: %v", perrs)
	}
	_, rerrs := resolver.Resolve(mod)
	if len(rerrs) > 0 {
		t.Fatalf("resolver errors: %v", rerrs)
	}
	result := desugar.Desugar(mod)
	out, err := Generate(result.Module, "test.golem")
	if err != nil {
		t.Fatalf("codegen error: %v", err)
	}
	return string(out)
}

// generateWithLoader runs the full pipeline including golifter with a real Go package loader.
func generateWithLoader(t *testing.T, source string) string {
	t.Helper()
	l := lexer.New(source, "test.golem")
	tokens := l.Tokenize()
	p := parser.New(tokens, "test.golem")
	mod, perrs := p.Parse()
	if len(perrs) > 0 {
		t.Fatalf("parse errors: %v", perrs)
	}
	res, rerrs := resolver.Resolve(mod)
	if len(rerrs) > 0 {
		t.Fatalf("resolver errors: %v", rerrs)
	}
	loader := goloader.New()
	lifted := golifter.Lift(mod, res, loader)
	result := desugar.Desugar(lifted)
	out, err := Generate(result.Module, "test.golem")
	if err != nil {
		t.Fatalf("codegen error: %v", err)
	}
	return string(out)
}

func assertContains(t *testing.T, got, want string) {
	t.Helper()
	if !strings.Contains(got, want) {
		t.Errorf("expected output to contain %q\ngot:\n%s", want, got)
	}
}

func assertNotContains(t *testing.T, got, notWant string) {
	t.Helper()
	if strings.Contains(got, notWant) {
		t.Errorf("expected output NOT to contain %q\ngot:\n%s", notWant, got)
	}
}

func TestFileHeader(t *testing.T) {
	out := generate(t, `pub fn main() do
  42
end`)
	assertContains(t, out, "// Code generated by golem. DO NOT EDIT.")
	assertContains(t, out, "// Source: test.golem")
	assertContains(t, out, "package main")
}

func TestSimpleFunction(t *testing.T) {
	out := generate(t, `pub fn greet(): String do
  "hello"
end`)
	assertContains(t, out, "func Greet() string")
	assertContains(t, out, `"hello"`)
}

func TestFunctionWithParams(t *testing.T) {
	out := generate(t, `pub fn add(a: Int, b: Int): Int do
  a + b
end`)
	assertContains(t, out, "func Add(a int, b int) int")
}

func TestLetBinding(t *testing.T) {
	out := generate(t, `pub fn main() do
  let x = 42
  x
end`)
	assertContains(t, out, "x := 42")
}

func TestBinaryExpressions(t *testing.T) {
	out := generate(t, `pub fn math(a: Int, b: Int): Int do
  a + b * 2
end`)
	assertContains(t, out, "+")
	assertContains(t, out, "*")
}

func TestStringConcat(t *testing.T) {
	out := generate(t, `pub fn greet(name: String): String do
  "hello " <> name
end`)
	// OpConcat desugars to + in Go
	assertContains(t, out, "+")
}

func TestComparison(t *testing.T) {
	out := generate(t, `pub fn isPositive(n: Int): Bool do
  n > 0
end`)
	assertContains(t, out, "func IsPositive(n int) bool")
	assertContains(t, out, ">")
}

func TestLogicalOperators(t *testing.T) {
	out := generate(t, `pub fn both(a: Bool, b: Bool): Bool do
  a && b
end`)
	assertContains(t, out, "&&")
}

func TestUnaryNeg(t *testing.T) {
	out := generate(t, `pub fn negate(n: Int): Int do
  -n
end`)
	assertContains(t, out, "(-n)")
}

func TestUnaryNot(t *testing.T) {
	out := generate(t, `pub fn invert(b: Bool): Bool do
  !b
end`)
	assertContains(t, out, "(!b)")
}

func TestFunctionCall(t *testing.T) {
	out := generate(t, `fn helper(): Int do
  42
end

pub fn main() do
  helper()
end`)
	assertContains(t, out, "helper()")
}

func TestQualifiedCall(t *testing.T) {
	out := generate(t, `import "fmt"

pub fn main() do
  fmt.println("hello")
end`)
	assertContains(t, out, `fmt.Println("hello")`)
	assertContains(t, out, `"fmt"`)
}

func TestIfElseStatement(t *testing.T) {
	out := generate(t, `pub fn check(n: Int) do
  if n > 0 do
    42
  end else do
    0
  end
end`)
	assertContains(t, out, "if")
	assertContains(t, out, "} else {")
}

func TestIfWithoutElse(t *testing.T) {
	out := generate(t, `import "fmt"

pub fn check(n: Int) do
  if n > 0 do
    fmt.println("positive")
  end
end`)
	assertContains(t, out, "if")
	assertNotContains(t, out, "else")
}

func TestIfExpressionInLet(t *testing.T) {
	out := generate(t, `pub fn classify(n: Int): Int do
  let x = if n > 0 do
    1
  end else do
    0
  end
  x
end`)
	// Should use result variable pattern
	assertContains(t, out, "var x int")
	assertContains(t, out, "x = 1")
	assertContains(t, out, "x = 0")
}

func TestProductType(t *testing.T) {
	out := generate(t, `pub type Point = { x: Float, y: Float }

pub fn main() do
  42
end`)
	assertContains(t, out, "type Point struct")
	assertContains(t, out, "X float64")
	assertContains(t, out, "Y float64")
}

func TestRecordLiteral(t *testing.T) {
	out := generate(t, `pub type Point = { x: Float, y: Float }

pub fn main() do
  Point { x: 1.0, y: 2.0 }
end`)
	assertContains(t, out, "Point{X: 1.0, Y: 2.0}")
}

func TestFieldAccess(t *testing.T) {
	out := generate(t, `pub type Point = { x: Float, y: Float }

pub fn getX(p: Point): Float do
  p.x
end`)
	assertContains(t, out, "p.X")
}

func TestImportSorting(t *testing.T) {
	out := generate(t, `import "net/http"
import "fmt"

pub fn main() do
  fmt.println("hello")
end`)
	fmtIdx := strings.Index(out, `"fmt"`)
	httpIdx := strings.Index(out, `"net/http"`)
	if fmtIdx > httpIdx {
		t.Errorf("expected fmt before net/http in import block")
	}
}

func TestVisibilityMapping(t *testing.T) {
	out := generate(t, `pub fn greet() do
  42
end

fn helper() do
  42
end`)
	assertContains(t, out, "func Greet()")
	assertContains(t, out, "func helper()")
}

func TestBoolLiterals(t *testing.T) {
	out := generate(t, `pub fn yes(): Bool do
  true
end

pub fn no(): Bool do
  false
end`)
	assertContains(t, out, "true")
	assertContains(t, out, "false")
}

func TestNilLiteral(t *testing.T) {
	out := generate(t, `pub fn nothing() do
  nil
end`)
	assertContains(t, out, "nil")
}

func TestAnonymousFunction(t *testing.T) {
	out := generate(t, `pub fn main() do
  let f = fn(x: Int): Int do x end
  f(42)
end`)
	assertContains(t, out, "func(x int) int")
}

func TestReturnExpr(t *testing.T) {
	out := generate(t, `pub fn early(n: Int): Int do
  if n > 0 do
    return n
  end
  0
end`)
	assertContains(t, out, "return n")
}

func TestQualifiedTypeInParam(t *testing.T) {
	out := generate(t, `import "net/http"

pub fn handle(w: http.ResponseWriter) do
  42
end`)
	assertContains(t, out, "w http.ResponseWriter")
}

func TestStringInterpolationDesugared(t *testing.T) {
	// After desugaring, string interpolation becomes fmt.Sprintf calls.
	out := generate(t, `pub fn greet(name: String): String do
  "Hello, #{name}!"
end`)
	assertContains(t, out, "fmt.Sprintf")
	assertContains(t, out, `"fmt"`)
}

func TestEmptyModule(t *testing.T) {
	// Should still produce valid Go with header and package.
	mod := &ast.Module{File: "empty.golem"}
	out, err := Generate(mod, "empty.golem")
	if err != nil {
		t.Fatalf("codegen error: %v", err)
	}
	s := string(out)
	assertContains(t, s, "package main")
	assertContains(t, s, "// Code generated by golem. DO NOT EDIT.")
}

func TestMultipleFunctions(t *testing.T) {
	out := generate(t, `pub fn foo(): Int do
  1
end

pub fn bar(): Int do
  2
end`)
	assertContains(t, out, "func Foo() int")
	assertContains(t, out, "func Bar() int")
}

// --- Sum types ---

func TestSumTypeCodeGen(t *testing.T) {
	out := generate(t, `pub type Shape =
  | Circle { radius: Float }
  | Rectangle { width: Float, height: Float }

pub fn main() do
  42
end`)
	// Sealed interface
	assertContains(t, out, "type Shape interface")
	assertContains(t, out, "isShape()")
	// Variant structs
	assertContains(t, out, "type ShapeCircle struct")
	assertContains(t, out, "Radius float64")
	assertContains(t, out, "type ShapeRectangle struct")
	assertContains(t, out, "Width")
	assertContains(t, out, "Height")
	// Marker methods
	assertContains(t, out, "func (ShapeCircle) isShape()")
	assertContains(t, out, "func (ShapeRectangle) isShape()")
}

func TestSumTypeUnitVariantCodeGen(t *testing.T) {
	out := generate(t, `pub type Color =
  | Red
  | Green
  | Blue

pub fn main() do
  42
end`)
	assertContains(t, out, "type Color interface")
	assertContains(t, out, "type ColorRed struct")
	assertContains(t, out, "type ColorGreen struct")
	assertContains(t, out, "type ColorBlue struct")
}

func TestSumTypeVariantConstruction(t *testing.T) {
	out := generate(t, `pub type Shape =
  | Circle { radius: Float }

pub fn main() do
  Circle { radius: 1.5 }
end`)
	assertContains(t, out, "ShapeCircle{Radius: 1.5}")
}

func TestSumTypeGeneratesValidGo(t *testing.T) {
	// The fact that Generate() doesn't error proves the output is valid Go syntax.
	_ = generate(t, `pub type Shape =
  | Circle { radius: Float }
  | Rectangle { width: Float, height: Float }
  | Point

pub fn main() do
  let c = Circle { radius: 3.14 }
  let r = Rectangle { width: 10.0, height: 5.0 }
  let p = Point
  42
end`)
}

func TestGoFormatProducesValidGo(t *testing.T) {
	// The fact that Generate() doesn't error proves the output is valid Go syntax.
	// This test exercises a more complex program.
	out := generate(t, `import "fmt"

pub type Point = { x: Float, y: Float }

pub fn main() do
  let p = Point { x: 1.0, y: 2.0 }
  fmt.println(p.x)
  if p.x > 0.0 do
    fmt.println("positive")
  end else do
    fmt.println("non-positive")
  end
end`)
	// Just verify it produced something reasonable.
	assertContains(t, out, "func main()")
	assertContains(t, out, "type Point struct")
}

// --- Match expression code generation ---

func TestMatchSumTypeSwitch(t *testing.T) {
	out := generate(t, `type Shape =
  | Circle { radius: Float }
  | Rectangle { width: Float, height: Float }

pub fn main() do
  let s: Shape = Circle { radius: 5.0 }
  match s do
    | Circle { radius } -> radius * radius
    | Rectangle { width, height } -> width * height
  end
end`)
	assertContains(t, out, "switch __match := s.(type)")
	assertContains(t, out, "case shapeCircle:")
	assertContains(t, out, "case shapeRectangle:")
	assertContains(t, out, "radius := __match.Radius")
	assertContains(t, out, "width := __match.Width")
	assertContains(t, out, "height := __match.Height")
}

func TestMatchUnitVariantCodegen(t *testing.T) {
	out := generate(t, `type Color =
  | Red
  | Green
  | Blue

pub fn name(c: Color): String do
  match c do
    | Red -> "red"
    | Green -> "green"
    | Blue -> "blue"
  end
end`)
	assertContains(t, out, "switch __match := c.(type)")
	assertContains(t, out, "case colorRed:")
	assertContains(t, out, "case colorGreen:")
	assertContains(t, out, "case colorBlue:")
}

func TestMatchLetAssign(t *testing.T) {
	out := generate(t, `type Shape =
  | Circle { radius: Float }
  | Square { side: Float }

pub fn area(s: Shape): Float do
  let result = match s do
    | Circle { radius } -> radius * radius
    | Square { side } -> side * side
  end
  result
end`)
	assertContains(t, out, "var result")
	assertContains(t, out, "switch __match := s.(type)")
	assertContains(t, out, "result =")
}

func TestMatchWildcardDefault(t *testing.T) {
	out := generate(t, `type Color =
  | Red
  | Green
  | Blue

pub fn isRed(c: Color): String do
  match c do
    | Red -> "yes"
    | _ -> "no"
  end
end`)
	assertContains(t, out, "case colorRed:")
	assertContains(t, out, "default:")
}

func TestMatchLiteralSwitch(t *testing.T) {
	out := generate(t, `pub fn describe(x: Int): String do
  match x do
    | 0 -> "zero"
    | 1 -> "one"
    | _ -> "other"
  end
end`)
	assertContains(t, out, "switch x {")
	assertContains(t, out, "case 0:")
	assertContains(t, out, "case 1:")
	assertContains(t, out, "default:")
}

// --- Generic type code generation ---

func TestGenericSumTypeCodegen(t *testing.T) {
	out := generate(t, `type Box<T> =
  | Full { value: T }
  | Empty`)
	assertContains(t, out, "type box[T any] interface")
	assertContains(t, out, "isbox()")
	assertContains(t, out, "type boxFull[T any] struct")
	assertContains(t, out, "type boxEmpty[T any] struct")
	assertContains(t, out, "func (boxFull[T]) isbox()")
	assertContains(t, out, "func (boxEmpty[T]) isbox()")
}

func TestGenericTwoParamSumTypeCodegen(t *testing.T) {
	out := generate(t, `type Either<L, R> =
  | Left { value: L }
  | Right { value: R }`)
	assertContains(t, out, "type either[L any, R any] interface")
	assertContains(t, out, "type eitherLeft[L any, R any] struct")
	assertContains(t, out, "type eitherRight[L any, R any] struct")
	assertContains(t, out, "func (eitherLeft[L, R]) iseither()")
	assertContains(t, out, "func (eitherRight[L, R]) iseither()")
}

func TestGenericFunctionCodegen(t *testing.T) {
	out := generate(t, `fn identity<A>(x: A): A do
  x
end`)
	assertContains(t, out, "func identity[A any](x A) A")
}

func TestGenericFunctionMultiParamCodegen(t *testing.T) {
	out := generate(t, `fn first<A, B>(a: A, b: B): A do
  a
end`)
	assertContains(t, out, "func first[A any, B any](a A, b B) A")
}

func TestGenericTypeApplicationInAnnotation(t *testing.T) {
	out := generate(t, `type Box<T> =
  | Full { value: T }
  | Empty

fn unbox(b: Box<Int>): Int do
  0
end`)
	assertContains(t, out, "func unbox(b box[int]) int")
}

// --- Built-in Result and Option codegen ---

func TestBuiltinResultCodegen(t *testing.T) {
	out := generate(t, `fn main() do
  Ok { value: 42 }
end`)
	assertContains(t, out, "type Result[T any, E any] interface")
	assertContains(t, out, "isResult()")
	assertContains(t, out, "type ResultOk[T any, E any] struct")
	assertContains(t, out, "type ResultErr[T any, E any] struct")
	assertContains(t, out, "func (ResultOk[T, E]) isResult()")
	assertContains(t, out, "func (ResultErr[T, E]) isResult()")
}

func TestBuiltinOptionCodegen(t *testing.T) {
	out := generate(t, `fn main() do
  Some { value: 42 }
end`)
	assertContains(t, out, "type Option[T any] interface")
	assertContains(t, out, "isOption()")
	assertContains(t, out, "type OptionSome[T any] struct")
	assertContains(t, out, "type OptionNone[T any] struct")
	assertContains(t, out, "func (OptionSome[T]) isOption()")
	assertContains(t, out, "func (OptionNone[T]) isOption()")
}

func TestBuiltinResultMatchCodegen(t *testing.T) {
	out := generate(t, `fn unwrap(r: Result<Int, String>): Int do
  match r do
    | Ok { value } -> value
    | Err { error } -> 0
  end
end`)
	assertContains(t, out, "switch __match := r.(type)")
	assertContains(t, out, "case ResultOk:")
	assertContains(t, out, "case ResultErr:")
}

func TestBuiltinOptionMatchCodegen(t *testing.T) {
	out := generate(t, `fn unwrap(o: Option<Int>): Int do
  match o do
    | Some { value } -> value
    | None -> 0
  end
end`)
	assertContains(t, out, "switch __match := o.(type)")
	assertContains(t, out, "case OptionSome:")
	assertContains(t, out, "case OptionNone:")
}

func TestBuiltinTypesNotEmittedWhenUnused(t *testing.T) {
	out := generate(t, `fn main() do
  42
end`)
	assertNotContains(t, out, "type Result")
	assertNotContains(t, out, "type Option")
}

// --- Error propagation (? operator) code generation ---

func TestErrorPropagationCodeGen(t *testing.T) {
	out := generate(t, `pub fn readContent(path: String): Result<String, String> do
  let content = readFile(path)?
  content
end

fn readFile(path: String): Result<String, String> do
  Ok { value: path }
end`)
	// Should generate a type switch on the result of readFile
	assertContains(t, out, "switch __match :=")
	// Ok arm unwraps the value
	assertContains(t, out, "ResultOk")
	// Err arm returns early
	assertContains(t, out, "ResultErr")
	assertContains(t, out, "return")
}

func TestErrorPropagationChainedCodeGen(t *testing.T) {
	out := generate(t, `pub fn process(path: String): Result<String, String> do
  let a = readFile(path)?
  let b = transform(a)?
  b
end

fn readFile(path: String): Result<String, String> do
  Ok { value: path }
end

fn transform(s: String): Result<String, String> do
  Ok { value: s }
end`)
	// Should have two type switches for the two ? operators
	switchCount := strings.Count(out, "switch __match :=")
	if switchCount < 2 {
		t.Errorf("expected at least 2 type switches for chained ?, got %d", switchCount)
	}
}

// --- GoLiftCallExpr code generation (auto-lifting (T, error) → Result) ---

func TestGoLiftCallExprEmitsIIFE(t *testing.T) {
	// Direct GoLiftCallExpr in a let statement.
	out := generateWithLoader(t, `import "os"

pub fn readBytes(path: String): String do
  os.readFile(path)
  path
end`)
	// The IIFE should wrap os.ReadFile and produce a Result.
	assertContains(t, out, "func() Result[")
	assertContains(t, out, "ResultOk[")
	assertContains(t, out, "ResultErr[")
	assertContains(t, out, "os.ReadFile(")
}

func TestGoLiftCallExprErrorOnlyIIFE(t *testing.T) {
	// net/http.ListenAndServe returns only error → Result[struct{}, error].
	out := generateWithLoader(t, `import "net/http"

pub fn serve(): String do
  http.listenAndServe(":8080", nil)
  "done"
end`)
	assertContains(t, out, "func() Result[struct{}, error]")
	assertContains(t, out, "ResultOk[struct{}, error]")
	assertContains(t, out, "ResultErr[struct{}, error]")
}

func TestGoLiftWithQuestionOperator(t *testing.T) {
	// ? on a lifted Go call: the type switch should have typed case labels.
	out := generateWithLoader(t, `import "os"

pub fn readContent(path: String): Result<List<Int>, Error> do
  let bytes = os.readFile(path)?
  Ok { value: 0 }
end`)
	// The IIFE wrapper should be present.
	assertContains(t, out, "func() Result[[]byte, error]")
	// Type switch cases should include generic type args.
	assertContains(t, out, "case ResultOk[[]byte, error]:")
	assertContains(t, out, "case ResultErr[[]byte, error]:")
}

func TestGoTypeNameErrorMapping(t *testing.T) {
	// Golem "Error" type name should generate lowercase Go "error".
	out := generate(t, `fn process(r: Result<Int, Error>): Int do
  match r do
    | Ok { value } -> value
    | Err { error } -> 0
  end
end`)
	assertContains(t, out, "Result[int, error]")
}

func TestResultCompositeWithTypeParams(t *testing.T) {
	// ResultOk/ResultErr literals in a function returning Result<T, E> should include type params.
	out := generate(t, `pub fn double(x: Int): Result<Int, Error> do
  Ok { value: x }
end`)
	assertContains(t, out, "ResultOk[int, error]")
}
