// Package codegen implements Go code generation from Golem's desugared AST.
//
// It walks the AST and emits Go source text using a printf-style string builder,
// then pipes the output through go/format.Source() for canonical formatting.
package codegen

import (
	"fmt"
	"go/format"
	"sort"
	"strings"
	"unicode"

	"github.com/dylanblakemore/golem/internal/ast"
)

// Go type name constants used in type mapping and inference.
const (
	goInt     = "int"
	goFloat64 = "float64"
	goString  = "string"
	goBool    = "bool"
	goAny     = "any"
)

// Built-in variant Go names (after desugaring).
const (
	builtinResultOk   = "ResultOk"
	builtinResultErr  = "ResultErr"
	builtinOptionSome = "OptionSome"
	builtinOptionNone = "OptionNone"
)

// Generate emits Go source code from a desugared Golem module.
// The sourceFile parameter is used in the generated header comment.
// Returns formatted Go source bytes or an error if formatting fails.
func Generate(mod *ast.Module, sourceFile string) ([]byte, error) {
	e := &emitter{
		imports: make(map[string]bool),
		source:  sourceFile,
	}

	// Collect imports from the module.
	for _, imp := range mod.Imports {
		e.imports[imp.Path] = true
	}

	// Emit declarations to a separate buffer so we can prepend the header.
	e.emitDecls(mod.Decls)
	e.emitBuiltinTypes(mod.Decls)
	body := e.buf.String()

	// Build the full file with header, package, imports, then body.
	var full strings.Builder
	full.WriteString("// Code generated by golem. DO NOT EDIT.\n")
	fmt.Fprintf(&full, "// Source: %s\n\n", sourceFile)
	full.WriteString("package main\n\n")

	// Import block.
	paths := sortedImports(e.imports)
	if len(paths) > 0 {
		full.WriteString("import (\n")
		for _, p := range paths {
			fmt.Fprintf(&full, "\t%q\n", p)
		}
		full.WriteString(")\n\n")
	}

	full.WriteString(body)

	return format.Source([]byte(full.String()))
}

type emitter struct {
	buf     strings.Builder
	indent  int
	imports map[string]bool
	source  string
}

func (e *emitter) linef(format string, args ...any) {
	fmt.Fprint(&e.buf, strings.Repeat("\t", e.indent))
	fmt.Fprintf(&e.buf, format, args...)
	e.buf.WriteByte('\n')
}

func (e *emitter) emitDecls(decls []ast.Decl) {
	for _, decl := range decls {
		e.emitDecl(decl)
		e.buf.WriteByte('\n')
	}
}

func (e *emitter) emitDecl(decl ast.Decl) {
	switch d := decl.(type) {
	case *ast.TypeDecl:
		e.emitTypeDecl(d)
	case *ast.FnDecl:
		e.emitFnDecl(d)
	case *ast.LetDecl:
		e.emitTopLetDecl(d)
	}
}

func (e *emitter) emitTypeDecl(td *ast.TypeDecl) {
	switch body := td.Body.(type) {
	case *ast.RecordTypeBody:
		e.linef("type %s struct {", td.Name)
		e.indent++
		for _, f := range body.Fields {
			e.linef("%s %s", exportField(f.Name), e.typeExpr(f.Type))
		}
		e.indent--
		e.linef("}")
	case *ast.SumTypeBody:
		e.emitSumTypeDecl(td.Name, td.TypeParams, body)
	}
}

func (e *emitter) emitSumTypeDecl(name string, typeParams []string, body *ast.SumTypeBody) {
	marker := "is" + name
	typeParamDecl := goTypeParamDecl(typeParams)
	typeParamUse := goTypeParamUse(typeParams)

	// Emit the sealed interface
	e.linef("type %s%s interface {", name, typeParamDecl)
	e.indent++
	e.linef("%s()", marker)
	e.indent--
	e.linef("}")

	// Emit each variant struct (names already prefixed by desugarer)
	for _, v := range body.Variants {
		e.buf.WriteByte('\n')
		e.linef("type %s%s struct {", v.Name, typeParamDecl)
		e.indent++
		for _, f := range v.Fields {
			e.linef("%s %s", exportField(f.Name), e.typeExpr(f.Type))
		}
		e.indent--
		e.linef("}")
		e.buf.WriteByte('\n')
		e.linef("func (%s%s) %s() {}", v.Name, typeParamUse, marker)
	}
}

func (e *emitter) emitFnDecl(fn *ast.FnDecl) {
	params := e.paramList(fn.Params)
	ret := ""
	if fn.ReturnType != nil {
		ret = " " + e.typeExpr(fn.ReturnType)
	}
	typeParamDecl := goTypeParamDecl(fn.TypeParams)

	e.linef("func %s%s(%s)%s {", fn.Name, typeParamDecl, params, ret)
	e.indent++
	e.emitBody(fn.Body)
	e.indent--
	e.linef("}")
}

func (e *emitter) emitTopLetDecl(ld *ast.LetDecl) {
	e.linef("var %s = %s", ld.Name, e.exprString(ld.Value))
}

func (e *emitter) paramList(params []*ast.Param) string {
	parts := make([]string, len(params))
	for i, p := range params {
		if p.Type != nil {
			parts[i] = p.Name + " " + e.typeExpr(p.Type)
		} else {
			parts[i] = p.Name
		}
	}
	return strings.Join(parts, ", ")
}

func (e *emitter) emitBody(stmts []ast.Expr) {
	for _, stmt := range stmts {
		e.emitStmt(stmt)
	}
}

func (e *emitter) emitStmt(expr ast.Expr) {
	switch s := expr.(type) {
	case *ast.LetExpr:
		e.emitLetStmt(s)
	case *ast.ReturnExpr:
		if s.Value != nil {
			e.linef("return %s", e.exprString(s.Value))
		} else {
			e.linef("return")
		}
	case *ast.IfExpr:
		e.emitIfStmt(s)
	case *ast.MatchExpr:
		e.emitMatchStmt(s)
	default:
		e.linef("%s", e.exprString(expr))
	}
}

func (e *emitter) emitLetStmt(le *ast.LetExpr) {
	// If the value is an IfExpr, use the result variable pattern.
	if ifExpr, ok := le.Value.(*ast.IfExpr); ok {
		e.emitIfAssign(le.Name, ifExpr)
		return
	}
	// If the value is a MatchExpr, use the result variable pattern.
	if matchExpr, ok := le.Value.(*ast.MatchExpr); ok {
		e.emitMatchAssign(le.Name, matchExpr)
		return
	}
	e.linef("%s := %s", le.Name, e.exprString(le.Value))
}

func (e *emitter) emitIfStmt(ie *ast.IfExpr) {
	e.linef("if %s {", e.exprString(ie.Cond))
	e.indent++
	e.emitBody(ie.Then)
	e.indent--
	if len(ie.Else) > 0 {
		e.linef("} else {")
		e.indent++
		e.emitBody(ie.Else)
		e.indent--
	}
	e.linef("}")
}

// emitIfAssign emits the result variable pattern for if-expressions in let bindings.
func (e *emitter) emitIfAssign(name string, ie *ast.IfExpr) {
	e.linef("var %s %s", name, e.inferGoType(ie))
	e.linef("if %s {", e.exprString(ie.Cond))
	e.indent++
	if len(ie.Then) > 0 {
		// All stmts except the last are emitted normally; the last assigns to the variable.
		for _, stmt := range ie.Then[:len(ie.Then)-1] {
			e.emitStmt(stmt)
		}
		e.linef("%s = %s", name, e.exprString(ie.Then[len(ie.Then)-1]))
	}
	e.indent--
	if len(ie.Else) > 0 {
		e.linef("} else {")
		e.indent++
		for _, stmt := range ie.Else[:len(ie.Else)-1] {
			e.emitStmt(stmt)
		}
		e.linef("%s = %s", name, e.exprString(ie.Else[len(ie.Else)-1]))
		e.indent--
	}
	e.linef("}")
}

// inferGoType attempts to determine the Go type string for an if-expression
// by inspecting the then branch's last expression. Falls back to any.
func (e *emitter) inferGoType(ie *ast.IfExpr) string {
	if len(ie.Then) == 0 {
		return goAny
	}
	return e.inferExprType(ie.Then[len(ie.Then)-1])
}

func (e *emitter) inferExprType(expr ast.Expr) string {
	switch ex := expr.(type) {
	case *ast.IntLit:
		return goInt
	case *ast.FloatLit:
		return goFloat64
	case *ast.StringLit:
		return goString
	case *ast.BoolLit:
		return goBool
	case *ast.BinaryExpr:
		switch ex.Op {
		case ast.OpEq, ast.OpNeq, ast.OpLt, ast.OpGt, ast.OpLte, ast.OpGte, ast.OpAnd, ast.OpOr:
			return goBool
		case ast.OpConcat:
			return goString
		default:
			return e.inferExprType(ex.Left)
		}
	default:
		return goAny
	}
}

//nolint:funlen,cyclop // type-switch over AST nodes is naturally long
func (e *emitter) exprString(expr ast.Expr) string {
	if expr == nil {
		return ""
	}

	switch ex := expr.(type) {
	case *ast.IntLit:
		return ex.Value
	case *ast.FloatLit:
		return ex.Value
	case *ast.StringLit:
		return fmt.Sprintf("%q", ex.Value)
	case *ast.BoolLit:
		if ex.Value {
			return "true"
		}
		return "false"
	case *ast.NilLit:
		return "nil"
	case *ast.Ident:
		return ex.Name
	case *ast.BinaryExpr:
		return e.binaryExpr(ex)
	case *ast.UnaryExpr:
		return e.unaryExpr(ex)
	case *ast.CallExpr:
		return e.callExpr(ex)
	case *ast.FieldAccessExpr:
		return fmt.Sprintf("%s.%s", e.exprString(ex.Expr), exportField(ex.Field))
	case *ast.RecordLit:
		return e.recordLit(ex)
	case *ast.BlockExpr:
		return e.blockExpr(ex)
	case *ast.IfExpr:
		// If-expressions in expression position use an IIFE.
		return e.ifExprIIFE(ex)
	case *ast.MatchExpr:
		return e.matchExprIIFE(ex)
	case *ast.FnLit:
		return e.fnLit(ex)
	case *ast.LetExpr:
		// Let in expression position shouldn't normally happen after desugaring,
		// but handle it gracefully.
		return fmt.Sprintf("%s := %s", ex.Name, e.exprString(ex.Value))
	case *ast.ReturnExpr:
		if ex.Value != nil {
			return "return " + e.exprString(ex.Value)
		}
		return "return"
	case *ast.BadExpr:
		return "/* bad expression */"
	default:
		return "/* unknown expression */"
	}
}

func (e *emitter) binaryExpr(be *ast.BinaryExpr) string {
	left := e.exprString(be.Left)
	right := e.exprString(be.Right)
	op := goOperator(be.Op)
	return fmt.Sprintf("(%s %s %s)", left, op, right)
}

func (e *emitter) unaryExpr(ue *ast.UnaryExpr) string {
	operand := e.exprString(ue.Operand)
	switch ue.Op {
	case ast.OpNeg:
		return fmt.Sprintf("(-%s)", operand)
	case ast.OpNot:
		return fmt.Sprintf("(!%s)", operand)
	default:
		return operand
	}
}

func (e *emitter) callExpr(ce *ast.CallExpr) string {
	fn := e.exprString(ce.Func)
	args := make([]string, len(ce.Args))
	for i, a := range ce.Args {
		args[i] = e.exprString(a)
	}
	return fmt.Sprintf("%s(%s)", fn, strings.Join(args, ", "))
}

func (e *emitter) recordLit(rl *ast.RecordLit) string {
	fields := make([]string, len(rl.Fields))
	for i, f := range rl.Fields {
		fields[i] = fmt.Sprintf("%s: %s", exportField(f.Name), e.exprString(f.Value))
	}
	return fmt.Sprintf("%s{%s}", rl.Name, strings.Join(fields, ", "))
}

func (e *emitter) blockExpr(be *ast.BlockExpr) string {
	if len(be.Stmts) == 1 {
		return e.exprString(be.Stmts[0])
	}
	// Multi-statement blocks in expression position use an IIFE.
	var b strings.Builder
	b.WriteString("func() any {\n")
	for i, stmt := range be.Stmts {
		if i == len(be.Stmts)-1 {
			fmt.Fprintf(&b, "return %s\n", e.exprString(stmt))
		} else {
			fmt.Fprintf(&b, "%s\n", e.exprString(stmt))
		}
	}
	b.WriteString("}()")
	return b.String()
}

func (e *emitter) ifExprIIFE(ie *ast.IfExpr) string {
	goType := e.inferGoType(ie)
	var b strings.Builder
	fmt.Fprintf(&b, "func() %s {\n", goType)
	b.WriteString("if ")
	b.WriteString(e.exprString(ie.Cond))
	b.WriteString(" {\n")
	for _, stmt := range ie.Then[:len(ie.Then)-1] {
		fmt.Fprintf(&b, "%s\n", e.exprString(stmt))
	}
	if len(ie.Then) > 0 {
		fmt.Fprintf(&b, "return %s\n", e.exprString(ie.Then[len(ie.Then)-1]))
	}
	b.WriteString("}")
	if len(ie.Else) > 0 {
		b.WriteString(" else {\n")
		for _, stmt := range ie.Else[:len(ie.Else)-1] {
			fmt.Fprintf(&b, "%s\n", e.exprString(stmt))
		}
		fmt.Fprintf(&b, "return %s\n", e.exprString(ie.Else[len(ie.Else)-1]))
		b.WriteString("}")
	}
	b.WriteString("\n}()")
	return b.String()
}

// isConstructorMatch returns true if the match has constructor patterns (sum type matching).
func isConstructorMatch(me *ast.MatchExpr) bool {
	for _, arm := range me.Arms {
		if _, ok := arm.Pattern.(*ast.ConstructorPattern); ok {
			return true
		}
	}
	return false
}

// emitMatchStmt emits a match expression in statement position.
func (e *emitter) emitMatchStmt(me *ast.MatchExpr) {
	if isConstructorMatch(me) {
		e.emitTypeSwitchStmt(me)
	} else {
		e.emitValueSwitchStmt(me)
	}
}

func (e *emitter) emitTypeSwitchStmt(me *ast.MatchExpr) {
	e.linef("switch __match := %s.(type) {", e.exprString(me.Scrutinee))
	for _, arm := range me.Arms {
		switch p := arm.Pattern.(type) {
		case *ast.ConstructorPattern:
			e.linef("case %s:", p.Constructor)
			e.indent++
			e.emitPatternBindings(p, "__match")
			e.emitBody(arm.Body)
			e.indent--
		case *ast.VarPattern:
			e.linef("default:")
			e.indent++
			e.linef("%s := __match", p.Name)
			e.emitBody(arm.Body)
			e.indent--
		case *ast.WildcardPattern:
			e.linef("default:")
			e.indent++
			e.emitBody(arm.Body)
			e.indent--
		}
	}
	e.linef("}")
}

func (e *emitter) emitValueSwitchStmt(me *ast.MatchExpr) {
	e.linef("switch %s {", e.exprString(me.Scrutinee))
	for _, arm := range me.Arms {
		switch p := arm.Pattern.(type) {
		case *ast.LiteralPattern:
			e.linef("case %s:", e.exprString(p.Value))
			e.indent++
			e.emitBody(arm.Body)
			e.indent--
		case *ast.VarPattern:
			e.linef("default:")
			e.indent++
			e.linef("%s := %s", p.Name, e.exprString(me.Scrutinee))
			e.emitBody(arm.Body)
			e.indent--
		case *ast.WildcardPattern:
			e.linef("default:")
			e.indent++
			e.emitBody(arm.Body)
			e.indent--
		}
	}
	e.linef("}")
}

func (e *emitter) emitPatternBindings(p *ast.ConstructorPattern, varName string) {
	for _, fp := range p.Fields {
		e.linef("%s := %s.%s", fp.Name, varName, exportField(fp.Name))
	}
}

// emitMatchAssign emits a match expression as a result variable assignment.
func (e *emitter) emitMatchAssign(name string, me *ast.MatchExpr) {
	goType := e.inferMatchType(me)
	e.linef("var %s %s", name, goType)
	if isConstructorMatch(me) {
		e.emitTypeSwitchAssign(name, me)
	} else {
		e.emitValueSwitchAssign(name, me)
	}
}

func (e *emitter) emitTypeSwitchAssign(name string, me *ast.MatchExpr) {
	e.linef("switch __match := %s.(type) {", e.exprString(me.Scrutinee))
	for _, arm := range me.Arms {
		switch p := arm.Pattern.(type) {
		case *ast.ConstructorPattern:
			e.linef("case %s:", p.Constructor)
			e.indent++
			e.emitPatternBindings(p, "__match")
			e.emitMatchArmAssign(name, arm.Body)
			e.indent--
		case *ast.VarPattern:
			e.linef("default:")
			e.indent++
			e.linef("%s := __match", p.Name)
			e.emitMatchArmAssign(name, arm.Body)
			e.indent--
		case *ast.WildcardPattern:
			e.linef("default:")
			e.indent++
			e.emitMatchArmAssign(name, arm.Body)
			e.indent--
		}
	}
	e.linef("}")
}

func (e *emitter) emitValueSwitchAssign(name string, me *ast.MatchExpr) {
	e.linef("switch %s {", e.exprString(me.Scrutinee))
	for _, arm := range me.Arms {
		switch p := arm.Pattern.(type) {
		case *ast.LiteralPattern:
			e.linef("case %s:", e.exprString(p.Value))
			e.indent++
			e.emitMatchArmAssign(name, arm.Body)
			e.indent--
		case *ast.VarPattern:
			e.linef("default:")
			e.indent++
			e.linef("%s := %s", p.Name, e.exprString(me.Scrutinee))
			e.emitMatchArmAssign(name, arm.Body)
			e.indent--
		case *ast.WildcardPattern:
			e.linef("default:")
			e.indent++
			e.emitMatchArmAssign(name, arm.Body)
			e.indent--
		}
	}
	e.linef("}")
}

func (e *emitter) emitMatchArmAssign(name string, body []ast.Expr) {
	if len(body) == 0 {
		return
	}
	for _, stmt := range body[:len(body)-1] {
		e.emitStmt(stmt)
	}
	e.linef("%s = %s", name, e.exprString(body[len(body)-1]))
}

func (e *emitter) matchExprIIFE(me *ast.MatchExpr) string {
	goType := e.inferMatchType(me)
	var b strings.Builder
	fmt.Fprintf(&b, "func() %s {\n", goType)
	if isConstructorMatch(me) {
		fmt.Fprintf(&b, "switch __match := %s.(type) {\n", e.exprString(me.Scrutinee))
		for _, arm := range me.Arms {
			switch p := arm.Pattern.(type) {
			case *ast.ConstructorPattern:
				fmt.Fprintf(&b, "case %s:\n", p.Constructor)
				for _, fp := range p.Fields {
					fmt.Fprintf(&b, "%s := __match.%s\n", fp.Name, exportField(fp.Name))
				}
				e.writeMatchArmReturn(&b, arm.Body)
			case *ast.VarPattern:
				b.WriteString("default:\n")
				fmt.Fprintf(&b, "%s := __match\n", p.Name)
				e.writeMatchArmReturn(&b, arm.Body)
			case *ast.WildcardPattern:
				b.WriteString("default:\n")
				e.writeMatchArmReturn(&b, arm.Body)
			}
		}
	} else {
		fmt.Fprintf(&b, "switch %s {\n", e.exprString(me.Scrutinee))
		for _, arm := range me.Arms {
			switch p := arm.Pattern.(type) {
			case *ast.LiteralPattern:
				fmt.Fprintf(&b, "case %s:\n", e.exprString(p.Value))
				e.writeMatchArmReturn(&b, arm.Body)
			case *ast.VarPattern:
				b.WriteString("default:\n")
				fmt.Fprintf(&b, "%s := %s\n", p.Name, e.exprString(me.Scrutinee))
				e.writeMatchArmReturn(&b, arm.Body)
			case *ast.WildcardPattern:
				b.WriteString("default:\n")
				e.writeMatchArmReturn(&b, arm.Body)
			}
		}
	}
	b.WriteString("}\nreturn *new(")
	b.WriteString(goType)
	b.WriteString(")\n}()")
	return b.String()
}

func (e *emitter) writeMatchArmReturn(b *strings.Builder, body []ast.Expr) {
	if len(body) == 0 {
		return
	}
	for _, stmt := range body[:len(body)-1] {
		fmt.Fprintf(b, "%s\n", e.exprString(stmt))
	}
	fmt.Fprintf(b, "return %s\n", e.exprString(body[len(body)-1]))
}

func (e *emitter) inferMatchType(me *ast.MatchExpr) string {
	if len(me.Arms) == 0 {
		return goAny
	}
	arm := me.Arms[0]
	if len(arm.Body) == 0 {
		return goAny
	}
	return e.inferExprType(arm.Body[len(arm.Body)-1])
}

func (e *emitter) fnLit(fl *ast.FnLit) string {
	params := e.paramList(fl.Params)
	ret := ""
	if fl.ReturnType != nil {
		ret = " " + e.typeExpr(fl.ReturnType)
	}
	var b strings.Builder
	fmt.Fprintf(&b, "func(%s)%s {\n", params, ret)
	for _, stmt := range fl.Body {
		fmt.Fprintf(&b, "%s\n", e.exprString(stmt))
	}
	b.WriteString("}")
	return b.String()
}

func (e *emitter) typeExpr(te ast.TypeExpr) string {
	if te == nil {
		return ""
	}
	switch t := te.(type) {
	case *ast.NamedType:
		return goTypeName(t.Name)
	case *ast.QualifiedType:
		return t.Qualifier + "." + t.Name
	case *ast.PointerType:
		return "*" + e.typeExpr(t.Elem)
	case *ast.FnType:
		params := make([]string, len(t.ParamTypes))
		for i, p := range t.ParamTypes {
			params[i] = e.typeExpr(p)
		}
		ret := ""
		if t.ReturnType != nil {
			ret = " " + e.typeExpr(t.ReturnType)
		}
		return fmt.Sprintf("func(%s)%s", strings.Join(params, ", "), ret)
	case *ast.GenericType:
		args := make([]string, len(t.TypeArgs))
		for i, a := range t.TypeArgs {
			args[i] = e.typeExpr(a)
		}
		return fmt.Sprintf("%s[%s]", goTypeName(t.Name), strings.Join(args, ", "))
	default:
		return goAny
	}
}

// emitBuiltinTypes emits Go type definitions for built-in types (Result, Option)
// only if they are referenced in the module's declarations.
func (e *emitter) emitBuiltinTypes(decls []ast.Decl) {
	needsResult, needsOption := scanForBuiltins(decls)

	if needsOption {
		e.buf.WriteByte('\n')
		e.emitSumTypeDecl("Option", []string{"T"}, &ast.SumTypeBody{
			Variants: []*ast.Variant{
				{Name: "OptionSome", Fields: []*ast.FieldDef{{Name: "value", Type: &ast.NamedType{Name: "T"}}}},
				{Name: "OptionNone", Fields: nil},
			},
		})
		e.buf.WriteByte('\n')
	}

	if needsResult {
		e.buf.WriteByte('\n')
		e.emitSumTypeDecl("Result", []string{"T", "E"}, &ast.SumTypeBody{
			Variants: []*ast.Variant{
				{Name: "ResultOk", Fields: []*ast.FieldDef{{Name: "value", Type: &ast.NamedType{Name: "T"}}}},
				{Name: "ResultErr", Fields: []*ast.FieldDef{{Name: "error", Type: &ast.NamedType{Name: "E"}}}},
			},
		})
		e.buf.WriteByte('\n')
	}
}

// scanForBuiltins checks if Result or Option variant names appear in the declarations.
func scanForBuiltins(decls []ast.Decl) (needsResult, needsOption bool) {
	for _, decl := range decls {
		scanExprForBuiltins(declExprs(decl), &needsResult, &needsOption)
		if needsResult && needsOption {
			return
		}
	}
	return
}

func declExprs(decl ast.Decl) []ast.Expr {
	switch d := decl.(type) {
	case *ast.FnDecl:
		return d.Body
	case *ast.LetDecl:
		return []ast.Expr{d.Value}
	default:
		return nil
	}
}

func scanExprForBuiltins(exprs []ast.Expr, needsResult, needsOption *bool) {
	for _, expr := range exprs {
		scanExpr(expr, needsResult, needsOption)
	}
}

//nolint:funlen,cyclop // scanning all expression kinds
func scanExpr(expr ast.Expr, needsResult, needsOption *bool) {
	if expr == nil {
		return
	}
	switch e := expr.(type) {
	case *ast.Ident:
		switch e.Name {
		case builtinResultOk, builtinResultErr:
			*needsResult = true
		case builtinOptionSome, builtinOptionNone:
			*needsOption = true
		}
	case *ast.RecordLit:
		switch e.Name {
		case builtinResultOk, builtinResultErr:
			*needsResult = true
		case builtinOptionSome, builtinOptionNone:
			*needsOption = true
		}
		for _, f := range e.Fields {
			scanExpr(f.Value, needsResult, needsOption)
		}
	case *ast.BinaryExpr:
		scanExpr(e.Left, needsResult, needsOption)
		scanExpr(e.Right, needsResult, needsOption)
	case *ast.UnaryExpr:
		scanExpr(e.Operand, needsResult, needsOption)
	case *ast.CallExpr:
		scanExpr(e.Func, needsResult, needsOption)
		scanExprForBuiltins(e.Args, needsResult, needsOption)
	case *ast.FieldAccessExpr:
		scanExpr(e.Expr, needsResult, needsOption)
	case *ast.BlockExpr:
		scanExprForBuiltins(e.Stmts, needsResult, needsOption)
	case *ast.IfExpr:
		scanExpr(e.Cond, needsResult, needsOption)
		scanExprForBuiltins(e.Then, needsResult, needsOption)
		scanExprForBuiltins(e.Else, needsResult, needsOption)
	case *ast.LetExpr:
		scanExpr(e.Value, needsResult, needsOption)
	case *ast.ReturnExpr:
		scanExpr(e.Value, needsResult, needsOption)
	case *ast.MatchExpr:
		scanExpr(e.Scrutinee, needsResult, needsOption)
		for _, arm := range e.Arms {
			scanPattern(arm.Pattern, needsResult, needsOption)
			scanExprForBuiltins(arm.Body, needsResult, needsOption)
		}
	case *ast.FnLit:
		scanExprForBuiltins(e.Body, needsResult, needsOption)
	}
}

func scanPattern(pat ast.Pattern, needsResult, needsOption *bool) {
	if cp, ok := pat.(*ast.ConstructorPattern); ok {
		switch cp.Constructor {
		case builtinResultOk, builtinResultErr:
			*needsResult = true
		case builtinOptionSome, builtinOptionNone:
			*needsOption = true
		}
	}
}

// goTypeParamDecl builds a Go type parameter declaration string, e.g. "[T any, E any]".
// Returns "" if there are no type params.
func goTypeParamDecl(typeParams []string) string {
	if len(typeParams) == 0 {
		return ""
	}
	parts := make([]string, len(typeParams))
	for i, tp := range typeParams {
		parts[i] = tp + " any"
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

// goTypeParamUse builds a Go type parameter usage string, e.g. "[T, E]".
// Returns "" if there are no type params.
func goTypeParamUse(typeParams []string) string {
	if len(typeParams) == 0 {
		return ""
	}
	return "[" + strings.Join(typeParams, ", ") + "]"
}

// goTypeName maps Golem built-in type names to Go type names.
func goTypeName(name string) string {
	switch name {
	case "Int":
		return goInt
	case "Float":
		return goFloat64
	case "String":
		return goString
	case "Bool":
		return goBool
	case "Any":
		return goAny
	default:
		return name
	}
}

// goOperator maps a Golem binary operator to its Go equivalent.
func goOperator(op ast.BinaryOp) string {
	switch op {
	case ast.OpAdd:
		return "+"
	case ast.OpSub:
		return "-"
	case ast.OpMul:
		return "*"
	case ast.OpDiv:
		return "/"
	case ast.OpMod:
		return "%"
	case ast.OpEq:
		return "=="
	case ast.OpNeq:
		return "!="
	case ast.OpLt:
		return "<"
	case ast.OpGt:
		return ">"
	case ast.OpLte:
		return "<="
	case ast.OpGte:
		return ">="
	case ast.OpAnd:
		return "&&"
	case ast.OpOr:
		return "||"
	case ast.OpConcat:
		return "+"
	default:
		return "?"
	}
}

// exportField capitalizes the first letter of a field name for Go export.
func exportField(name string) string {
	if len(name) == 0 {
		return name
	}
	runes := []rune(name)
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

func sortedImports(imports map[string]bool) []string {
	paths := make([]string, 0, len(imports))
	for p := range imports {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	return paths
}
