package codegen

import (
	"strings"
	"testing"

	"github.com/dylanblakemore/golem/internal/ast"
	"github.com/dylanblakemore/golem/internal/desugar"
	"github.com/dylanblakemore/golem/internal/lexer"
	"github.com/dylanblakemore/golem/internal/parser"
	"github.com/dylanblakemore/golem/internal/resolver"
)

// generate runs the full pipeline: lex -> parse -> resolve -> desugar -> generate.
func generate(t *testing.T, source string) string {
	t.Helper()
	l := lexer.New(source, "test.golem")
	tokens := l.Tokenize()
	p := parser.New(tokens, "test.golem")
	mod, perrs := p.Parse()
	if len(perrs) > 0 {
		t.Fatalf("parse errors: %v", perrs)
	}
	_, rerrs := resolver.Resolve(mod)
	if len(rerrs) > 0 {
		t.Fatalf("resolver errors: %v", rerrs)
	}
	result := desugar.Desugar(mod)
	out, err := Generate(result.Module, "test.golem")
	if err != nil {
		t.Fatalf("codegen error: %v", err)
	}
	return string(out)
}

func assertContains(t *testing.T, got, want string) {
	t.Helper()
	if !strings.Contains(got, want) {
		t.Errorf("expected output to contain %q\ngot:\n%s", want, got)
	}
}

func assertNotContains(t *testing.T, got, notWant string) {
	t.Helper()
	if strings.Contains(got, notWant) {
		t.Errorf("expected output NOT to contain %q\ngot:\n%s", notWant, got)
	}
}

func TestFileHeader(t *testing.T) {
	out := generate(t, `pub fn main() do
  42
end`)
	assertContains(t, out, "// Code generated by golem. DO NOT EDIT.")
	assertContains(t, out, "// Source: test.golem")
	assertContains(t, out, "package main")
}

func TestSimpleFunction(t *testing.T) {
	out := generate(t, `pub fn greet(): String do
  "hello"
end`)
	assertContains(t, out, "func Greet() string")
	assertContains(t, out, `"hello"`)
}

func TestFunctionWithParams(t *testing.T) {
	out := generate(t, `pub fn add(a: Int, b: Int): Int do
  a + b
end`)
	assertContains(t, out, "func Add(a int, b int) int")
}

func TestLetBinding(t *testing.T) {
	out := generate(t, `pub fn main() do
  let x = 42
  x
end`)
	assertContains(t, out, "x := 42")
}

func TestBinaryExpressions(t *testing.T) {
	out := generate(t, `pub fn math(a: Int, b: Int): Int do
  a + b * 2
end`)
	assertContains(t, out, "+")
	assertContains(t, out, "*")
}

func TestStringConcat(t *testing.T) {
	out := generate(t, `pub fn greet(name: String): String do
  "hello " <> name
end`)
	// OpConcat desugars to + in Go
	assertContains(t, out, "+")
}

func TestComparison(t *testing.T) {
	out := generate(t, `pub fn isPositive(n: Int): Bool do
  n > 0
end`)
	assertContains(t, out, "func IsPositive(n int) bool")
	assertContains(t, out, ">")
}

func TestLogicalOperators(t *testing.T) {
	out := generate(t, `pub fn both(a: Bool, b: Bool): Bool do
  a && b
end`)
	assertContains(t, out, "&&")
}

func TestUnaryNeg(t *testing.T) {
	out := generate(t, `pub fn negate(n: Int): Int do
  -n
end`)
	assertContains(t, out, "(-n)")
}

func TestUnaryNot(t *testing.T) {
	out := generate(t, `pub fn invert(b: Bool): Bool do
  !b
end`)
	assertContains(t, out, "(!b)")
}

func TestFunctionCall(t *testing.T) {
	out := generate(t, `fn helper(): Int do
  42
end

pub fn main() do
  helper()
end`)
	assertContains(t, out, "helper()")
}

func TestQualifiedCall(t *testing.T) {
	out := generate(t, `import "fmt"

pub fn main() do
  fmt.println("hello")
end`)
	assertContains(t, out, `fmt.Println("hello")`)
	assertContains(t, out, `"fmt"`)
}

func TestIfElseStatement(t *testing.T) {
	out := generate(t, `pub fn check(n: Int) do
  if n > 0 do
    42
  end else do
    0
  end
end`)
	assertContains(t, out, "if")
	assertContains(t, out, "} else {")
}

func TestIfWithoutElse(t *testing.T) {
	out := generate(t, `import "fmt"

pub fn check(n: Int) do
  if n > 0 do
    fmt.println("positive")
  end
end`)
	assertContains(t, out, "if")
	assertNotContains(t, out, "else")
}

func TestIfExpressionInLet(t *testing.T) {
	out := generate(t, `pub fn classify(n: Int): Int do
  let x = if n > 0 do
    1
  end else do
    0
  end
  x
end`)
	// Should use result variable pattern
	assertContains(t, out, "var x int")
	assertContains(t, out, "x = 1")
	assertContains(t, out, "x = 0")
}

func TestProductType(t *testing.T) {
	out := generate(t, `pub type Point = { x: Float, y: Float }

pub fn main() do
  42
end`)
	assertContains(t, out, "type Point struct")
	assertContains(t, out, "X float64")
	assertContains(t, out, "Y float64")
}

func TestRecordLiteral(t *testing.T) {
	out := generate(t, `pub type Point = { x: Float, y: Float }

pub fn main() do
  Point { x: 1.0, y: 2.0 }
end`)
	assertContains(t, out, "Point{X: 1.0, Y: 2.0}")
}

func TestFieldAccess(t *testing.T) {
	out := generate(t, `pub type Point = { x: Float, y: Float }

pub fn getX(p: Point): Float do
  p.x
end`)
	assertContains(t, out, "p.X")
}

func TestImportSorting(t *testing.T) {
	out := generate(t, `import "net/http"
import "fmt"

pub fn main() do
  fmt.println("hello")
end`)
	fmtIdx := strings.Index(out, `"fmt"`)
	httpIdx := strings.Index(out, `"net/http"`)
	if fmtIdx > httpIdx {
		t.Errorf("expected fmt before net/http in import block")
	}
}

func TestVisibilityMapping(t *testing.T) {
	out := generate(t, `pub fn greet() do
  42
end

fn helper() do
  42
end`)
	assertContains(t, out, "func Greet()")
	assertContains(t, out, "func helper()")
}

func TestBoolLiterals(t *testing.T) {
	out := generate(t, `pub fn yes(): Bool do
  true
end

pub fn no(): Bool do
  false
end`)
	assertContains(t, out, "true")
	assertContains(t, out, "false")
}

func TestNilLiteral(t *testing.T) {
	out := generate(t, `pub fn nothing() do
  nil
end`)
	assertContains(t, out, "nil")
}

func TestAnonymousFunction(t *testing.T) {
	out := generate(t, `pub fn main() do
  let f = fn(x: Int): Int do x end
  f(42)
end`)
	assertContains(t, out, "func(x int) int")
}

func TestReturnExpr(t *testing.T) {
	out := generate(t, `pub fn early(n: Int): Int do
  if n > 0 do
    return n
  end
  0
end`)
	assertContains(t, out, "return n")
}

func TestQualifiedTypeInParam(t *testing.T) {
	out := generate(t, `import "net/http"

pub fn handle(w: http.ResponseWriter) do
  42
end`)
	assertContains(t, out, "w http.ResponseWriter")
}

func TestStringInterpolationDesugared(t *testing.T) {
	// After desugaring, string interpolation becomes fmt.Sprintf calls.
	out := generate(t, `pub fn greet(name: String): String do
  "Hello, #{name}!"
end`)
	assertContains(t, out, "fmt.Sprintf")
	assertContains(t, out, `"fmt"`)
}

func TestEmptyModule(t *testing.T) {
	// Should still produce valid Go with header and package.
	mod := &ast.Module{File: "empty.golem"}
	out, err := Generate(mod, "empty.golem")
	if err != nil {
		t.Fatalf("codegen error: %v", err)
	}
	s := string(out)
	assertContains(t, s, "package main")
	assertContains(t, s, "// Code generated by golem. DO NOT EDIT.")
}

func TestMultipleFunctions(t *testing.T) {
	out := generate(t, `pub fn foo(): Int do
  1
end

pub fn bar(): Int do
  2
end`)
	assertContains(t, out, "func Foo() int")
	assertContains(t, out, "func Bar() int")
}

func TestGoFormatProducesValidGo(t *testing.T) {
	// The fact that Generate() doesn't error proves the output is valid Go syntax.
	// This test exercises a more complex program.
	out := generate(t, `import "fmt"

pub type Point = { x: Float, y: Float }

pub fn main() do
  let p = Point { x: 1.0, y: 2.0 }
  fmt.println(p.x)
  if p.x > 0.0 do
    fmt.println("positive")
  end else do
    fmt.println("non-positive")
  end
end`)
	// Just verify it produced something reasonable.
	assertContains(t, out, "func main()")
	assertContains(t, out, "type Point struct")
}
