// Package codegen implements Go code generation from Golem's desugared AST.
//
// It walks the AST and emits Go source text using a printf-style string builder,
// then pipes the output through go/format.Source() for canonical formatting.
package codegen

import (
	"fmt"
	"go/format"
	"sort"
	"strings"
	"unicode"

	"github.com/dylanblakemore/golem/internal/ast"
)

// Go type name constants used in type mapping and inference.
const (
	goInt     = "int"
	goFloat64 = "float64"
	goString  = "string"
	goBool    = "bool"
	goAny     = "any"
)

// Built-in variant Go names (after desugaring).
const (
	builtinResultOk   = "ResultOk"
	builtinResultErr  = "ResultErr"
	builtinOptionSome = "OptionSome"
	builtinOptionNone = "OptionNone"
)

// Generate emits Go source code from a desugared Golem module.
// The sourceFile parameter is used in the generated header comment.
// Returns formatted Go source bytes or an error if formatting fails.
func Generate(mod *ast.Module, sourceFile string) ([]byte, error) {
	e := &emitter{
		imports: make(map[string]bool),
		source:  sourceFile,
	}

	// Collect imports from the module.
	for _, imp := range mod.Imports {
		e.imports[imp.Path] = true
	}

	// Emit declarations to a separate buffer so we can prepend the header.
	e.emitDecls(mod.Decls)
	e.emitBuiltinTypes(mod.Decls)
	body := e.buf.String()

	// Build the full file with header, package, imports, then body.
	var full strings.Builder
	full.WriteString("// Code generated by golem. DO NOT EDIT.\n")
	fmt.Fprintf(&full, "// Source: %s\n\n", sourceFile)
	full.WriteString("package main\n\n")

	// Import block.
	paths := sortedImports(e.imports)
	if len(paths) > 0 {
		full.WriteString("import (\n")
		for _, p := range paths {
			fmt.Fprintf(&full, "\t%q\n", p)
		}
		full.WriteString(")\n\n")
	}

	full.WriteString(body)

	return format.Source([]byte(full.String()))
}

type emitter struct {
	buf     strings.Builder
	indent  int
	imports map[string]bool
	source  string

	// liftedVars tracks variables bound from GoLiftCallExpr values.
	// Maps variable name → Go value type string (e.g. "[]byte"), or "" for error-only.
	liftedVars map[string]string
	// resultTypeParams is set when the current function returns Result[T, E].
	// It holds the joined type args string, e.g. "string, error".
	resultTypeParams string
}

func (e *emitter) linef(format string, args ...any) {
	fmt.Fprint(&e.buf, strings.Repeat("\t", e.indent))
	fmt.Fprintf(&e.buf, format, args...)
	e.buf.WriteByte('\n')
}

func (e *emitter) emitDecls(decls []ast.Decl) {
	for _, decl := range decls {
		e.emitDecl(decl)
		e.buf.WriteByte('\n')
	}
}

func (e *emitter) emitDecl(decl ast.Decl) {
	switch d := decl.(type) {
	case *ast.TypeDecl:
		e.emitTypeDecl(d)
	case *ast.FnDecl:
		e.emitFnDecl(d)
	case *ast.LetDecl:
		e.emitTopLetDecl(d)
	}
}

func (e *emitter) emitTypeDecl(td *ast.TypeDecl) {
	switch body := td.Body.(type) {
	case *ast.RecordTypeBody:
		e.linef("type %s struct {", td.Name)
		e.indent++
		for _, f := range body.Fields {
			e.linef("%s %s", exportField(f.Name), e.typeExpr(f.Type))
		}
		e.indent--
		e.linef("}")
	case *ast.SumTypeBody:
		e.emitSumTypeDecl(td.Name, td.TypeParams, body)
	}
}

func (e *emitter) emitSumTypeDecl(name string, typeParams []string, body *ast.SumTypeBody) {
	marker := "is" + name
	typeParamDecl := goTypeParamDecl(typeParams)
	typeParamUse := goTypeParamUse(typeParams)

	// Emit the sealed interface
	e.linef("type %s%s interface {", name, typeParamDecl)
	e.indent++
	e.linef("%s()", marker)
	e.indent--
	e.linef("}")

	// Emit each variant struct (names already prefixed by desugarer)
	for _, v := range body.Variants {
		e.buf.WriteByte('\n')
		e.linef("type %s%s struct {", v.Name, typeParamDecl)
		e.indent++
		for _, f := range v.Fields {
			e.linef("%s %s", exportField(f.Name), e.typeExpr(f.Type))
		}
		e.indent--
		e.linef("}")
		e.buf.WriteByte('\n')
		e.linef("func (%s%s) %s() {}", v.Name, typeParamUse, marker)
	}
}

func (e *emitter) emitFnDecl(fn *ast.FnDecl) {
	params := e.paramList(fn.Params)
	ret := ""
	if fn.ReturnType != nil {
		ret = " " + e.typeExpr(fn.ReturnType)
	}
	typeParamDecl := goTypeParamDecl(fn.TypeParams)

	// Track Result type params for the duration of this function so that
	// ResultOk/ResultErr composite literals and return statements can include them.
	prevResultTypeParams := e.resultTypeParams
	prevLiftedVars := e.liftedVars
	e.resultTypeParams = extractResultTypeParams(fn.ReturnType, e)
	e.liftedVars = make(map[string]string)

	e.linef("func %s%s(%s)%s {", fn.Name, typeParamDecl, params, ret)
	e.indent++
	e.emitBodyWithTail(fn.Body, fn.ReturnType != nil)
	e.indent--
	e.linef("}")

	e.resultTypeParams = prevResultTypeParams
	e.liftedVars = prevLiftedVars
}

// extractResultTypeParams returns the comma-joined Go type argument string for a
// function whose return type is Result<T, E>, or "" for any other return type.
func extractResultTypeParams(retType ast.TypeExpr, e *emitter) string {
	gt, ok := retType.(*ast.GenericType)
	if !ok {
		return ""
	}
	if gt.Name != "Result" || len(gt.TypeArgs) != resultTypeArgCount {
		return ""
	}
	return e.typeExpr(gt.TypeArgs[0]) + ", " + e.typeExpr(gt.TypeArgs[1])
}

// resultTypeArgCount is the expected number of type args for Result<T, E>.
const resultTypeArgCount = 2

func (e *emitter) emitTopLetDecl(ld *ast.LetDecl) {
	e.linef("var %s = %s", ld.Name, e.exprString(ld.Value))
}

func (e *emitter) paramList(params []*ast.Param) string {
	parts := make([]string, len(params))
	for i, p := range params {
		if p.Type != nil {
			parts[i] = p.Name + " " + e.typeExpr(p.Type)
		} else {
			parts[i] = p.Name
		}
	}
	return strings.Join(parts, ", ")
}

func (e *emitter) emitBody(stmts []ast.Expr) {
	for _, stmt := range stmts {
		e.emitStmt(stmt)
	}
}

// emitBodyWithTail emits all but the last statement normally, then emits the
// last statement in tail position (with return semantics) when withReturn is true.
func (e *emitter) emitBodyWithTail(stmts []ast.Expr, withReturn bool) {
	if !withReturn || len(stmts) == 0 {
		e.emitBody(stmts)
		return
	}
	e.emitBody(stmts[:len(stmts)-1])
	e.emitTailStmt(stmts[len(stmts)-1])
}

// emitTailStmt emits a statement in tail position, adding return semantics.
func (e *emitter) emitTailStmt(expr ast.Expr) {
	switch s := expr.(type) {
	case *ast.ReturnExpr:
		e.emitStmt(s) // already explicit return
	case *ast.MatchExpr:
		e.emitMatchReturn(s)
	case *ast.IfExpr:
		e.emitIfReturn(s)
	case *ast.LetExpr:
		e.emitStmt(s) // let in tail position: value is discarded
	default:
		e.linef("return %s", e.exprString(expr))
	}
}

// emitMatchReturn emits a match expression in tail-return position.
func (e *emitter) emitMatchReturn(me *ast.MatchExpr) {
	if hasGuard(me) {
		e.emitGuardedMatchReturn(me)
		return
	}
	if isConstructorMatch(me) {
		e.emitTypeSwitchReturn(me)
	} else {
		e.emitValueSwitchReturn(me)
	}
}

func (e *emitter) emitTypeSwitchReturn(me *ast.MatchExpr) {
	scrutineeName := identName(me.Scrutinee)
	groups := groupArmsByConstructor(me.Arms)
	hasDefault := false
	e.linef("switch __match := %s.(type) {", e.exprString(me.Scrutinee))
	for _, g := range groups {
		if g.isDefault {
			hasDefault = true
		}
		e.emitArmGroup(g, "__match", scrutineeName, 0, func(arm *ast.MatchArm) {
			e.emitMatchArmReturn(arm.Body)
		})
	}
	e.linef("}")
	if !hasDefault {
		e.linef(`panic("unreachable")`)
	}
}

func (e *emitter) emitValueSwitchReturn(me *ast.MatchExpr) {
	e.emitValueSwitch(me, func(arm *ast.MatchArm) {
		e.emitMatchArmReturn(arm.Body)
	})
	if !hasValueSwitchDefault(me) {
		e.linef(`panic("unreachable")`)
	}
}

// hasValueSwitchDefault reports whether a value-based match contains a
// default arm (var or wildcard pattern) covering all non-matched values.
func hasValueSwitchDefault(me *ast.MatchExpr) bool {
	for _, arm := range me.Arms {
		switch arm.Pattern.(type) {
		case *ast.VarPattern, *ast.WildcardPattern:
			return true
		}
	}
	return false
}

// emitArmLead emits all body statements except the last and returns the last
// expression (or nil for an empty body). Callers decide how to render the
// tail based on emission context (return, assign, break, etc.).
func (e *emitter) emitArmLead(body []ast.Expr) ast.Expr {
	if len(body) == 0 {
		return nil
	}
	for _, s := range body[:len(body)-1] {
		e.emitStmt(s)
	}
	return body[len(body)-1]
}

// emitMatchArmReturn emits the body of a match arm in tail-return position.
func (e *emitter) emitMatchArmReturn(body []ast.Expr) {
	last := e.emitArmLead(body)
	if last == nil {
		return
	}
	if _, isReturn := last.(*ast.ReturnExpr); isReturn {
		e.emitStmt(last)
		return
	}
	e.linef("return %s", e.exprString(last))
}

// emitIfReturn emits an if expression in tail-return position.
func (e *emitter) emitIfReturn(ie *ast.IfExpr) {
	e.linef("if %s {", e.exprString(ie.Cond))
	e.indent++
	e.emitBodyWithTail(ie.Then, true)
	e.indent--
	if len(ie.Else) > 0 {
		e.linef("} else {")
		e.indent++
		e.emitBodyWithTail(ie.Else, true)
		e.indent--
	}
	e.linef("}")
}

func (e *emitter) emitStmt(expr ast.Expr) {
	switch s := expr.(type) {
	case *ast.LetExpr:
		e.emitLetStmt(s)
	case *ast.ReturnExpr:
		if s.Value != nil {
			e.linef("return %s", e.exprString(s.Value))
		} else {
			e.linef("return")
		}
	case *ast.IfExpr:
		e.emitIfStmt(s)
	case *ast.MatchExpr:
		e.emitMatchStmt(s)
	default:
		e.linef("%s", e.exprString(expr))
	}
}

func (e *emitter) emitLetStmt(le *ast.LetExpr) {
	// If the value is an IfExpr, use the result variable pattern.
	if ifExpr, ok := le.Value.(*ast.IfExpr); ok {
		e.emitIfAssign(le.Name, ifExpr)
		return
	}
	// If the value is a MatchExpr, use the result variable pattern.
	if matchExpr, ok := le.Value.(*ast.MatchExpr); ok {
		e.emitMatchAssign(le.Name, matchExpr)
		return
	}
	// Track variables bound from GoLiftCallExpr so type switch cases can use
	// the correct generic type arguments.
	if lift, ok := le.Value.(*ast.GoLiftCallExpr); ok {
		if e.liftedVars != nil {
			e.liftedVars[le.Name] = lift.ValueGoType
		}
	}
	if le.Name == "_" {
		// Blank identifier: use assignment not short variable declaration.
		e.linef("_ = %s", e.exprString(le.Value))
		return
	}
	e.linef("%s := %s", le.Name, e.exprString(le.Value))
}

func (e *emitter) emitIfStmt(ie *ast.IfExpr) {
	e.linef("if %s {", e.exprString(ie.Cond))
	e.indent++
	e.emitBody(ie.Then)
	e.indent--
	if len(ie.Else) > 0 {
		e.linef("} else {")
		e.indent++
		e.emitBody(ie.Else)
		e.indent--
	}
	e.linef("}")
}

// emitIfAssign emits the result variable pattern for if-expressions in let bindings.
func (e *emitter) emitIfAssign(name string, ie *ast.IfExpr) {
	e.linef("var %s %s", name, e.inferGoType(ie))
	e.linef("if %s {", e.exprString(ie.Cond))
	e.indent++
	if len(ie.Then) > 0 {
		// All stmts except the last are emitted normally; the last assigns to the variable.
		for _, stmt := range ie.Then[:len(ie.Then)-1] {
			e.emitStmt(stmt)
		}
		e.linef("%s = %s", name, e.exprString(ie.Then[len(ie.Then)-1]))
	}
	e.indent--
	if len(ie.Else) > 0 {
		e.linef("} else {")
		e.indent++
		for _, stmt := range ie.Else[:len(ie.Else)-1] {
			e.emitStmt(stmt)
		}
		e.linef("%s = %s", name, e.exprString(ie.Else[len(ie.Else)-1]))
		e.indent--
	}
	e.linef("}")
}

// inferGoType attempts to determine the Go type string for an if-expression
// by inspecting the then branch's last expression. Falls back to any.
func (e *emitter) inferGoType(ie *ast.IfExpr) string {
	if len(ie.Then) == 0 {
		return goAny
	}
	return e.inferExprType(ie.Then[len(ie.Then)-1])
}

func (e *emitter) inferExprType(expr ast.Expr) string {
	switch ex := expr.(type) {
	case *ast.IntLit:
		return goInt
	case *ast.FloatLit:
		return goFloat64
	case *ast.StringLit:
		return goString
	case *ast.BoolLit:
		return goBool
	case *ast.BinaryExpr:
		switch ex.Op {
		case ast.OpEq, ast.OpNeq, ast.OpLt, ast.OpGt, ast.OpLte, ast.OpGte, ast.OpAnd, ast.OpOr:
			return goBool
		case ast.OpConcat:
			return goString
		default:
			return e.inferExprType(ex.Left)
		}
	default:
		return goAny
	}
}

//nolint:funlen,cyclop // type-switch over AST nodes is naturally long
func (e *emitter) exprString(expr ast.Expr) string {
	if expr == nil {
		return ""
	}

	switch ex := expr.(type) {
	case *ast.IntLit:
		return ex.Value
	case *ast.FloatLit:
		return ex.Value
	case *ast.StringLit:
		return fmt.Sprintf("%q", ex.Value)
	case *ast.BoolLit:
		if ex.Value {
			return "true"
		}
		return "false"
	case *ast.NilLit:
		return "nil"
	case *ast.Ident:
		return ex.Name
	case *ast.BinaryExpr:
		return e.binaryExpr(ex)
	case *ast.UnaryExpr:
		return e.unaryExpr(ex)
	case *ast.CallExpr:
		return e.callExpr(ex)
	case *ast.FieldAccessExpr:
		return fmt.Sprintf("%s.%s", e.exprString(ex.Expr), exportField(ex.Field))
	case *ast.RecordLit:
		return e.recordLit(ex)
	case *ast.BlockExpr:
		return e.blockExpr(ex)
	case *ast.IfExpr:
		// If-expressions in expression position use an IIFE.
		return e.ifExprIIFE(ex)
	case *ast.MatchExpr:
		return e.matchExprIIFE(ex)
	case *ast.FnLit:
		return e.fnLit(ex)
	case *ast.LetExpr:
		// Let in expression position shouldn't normally happen after desugaring,
		// but handle it gracefully.
		return fmt.Sprintf("%s := %s", ex.Name, e.exprString(ex.Value))
	case *ast.ReturnExpr:
		if ex.Value != nil {
			return "return " + e.exprString(ex.Value)
		}
		return "return"
	case *ast.GoLiftCallExpr:
		return e.goLiftCallExpr(ex)
	case *ast.BadExpr:
		return "/* bad expression */"
	default:
		return "/* unknown expression */"
	}
}

// goLiftCallExpr emits an IIFE that converts a Go (T, error) or error-only call
// into a Result value, allowing it to be used in expression position.
func (e *emitter) goLiftCallExpr(lift *ast.GoLiftCallExpr) string {
	call := e.exprString(lift.Call)
	if lift.ValueGoType == "" {
		// error-only: Result[struct{}, error]
		const errOnlyFmt = "func() Result[struct{}, error] {" +
			" if __e := %s; __e != nil { return ResultErr[struct{}, error]{Error: __e} };" +
			" return ResultOk[struct{}, error]{} }()"
		return fmt.Sprintf(errOnlyFmt, call)
	}
	vt := lift.ValueGoType
	const tupleFmt = "func() Result[%s, error] {" +
		" __v, __e := %s;" +
		" if __e != nil { return ResultErr[%s, error]{Error: __e} };" +
		" return ResultOk[%s, error]{Value: __v} }()"
	return fmt.Sprintf(tupleFmt, vt, call, vt, vt)
}

func (e *emitter) binaryExpr(be *ast.BinaryExpr) string {
	left := e.exprString(be.Left)
	right := e.exprString(be.Right)
	op := goOperator(be.Op)
	return fmt.Sprintf("(%s %s %s)", left, op, right)
}

func (e *emitter) unaryExpr(ue *ast.UnaryExpr) string {
	operand := e.exprString(ue.Operand)
	switch ue.Op {
	case ast.OpNeg:
		return fmt.Sprintf("(-%s)", operand)
	case ast.OpNot:
		return fmt.Sprintf("(!%s)", operand)
	default:
		return operand
	}
}

func (e *emitter) callExpr(ce *ast.CallExpr) string {
	fn := e.exprString(ce.Func)
	args := make([]string, len(ce.Args))
	for i, a := range ce.Args {
		args[i] = e.exprString(a)
	}
	return fmt.Sprintf("%s(%s)", fn, strings.Join(args, ", "))
}

func (e *emitter) recordLit(rl *ast.RecordLit) string {
	fields := make([]string, len(rl.Fields))
	for i, f := range rl.Fields {
		fields[i] = fmt.Sprintf("%s: %s", exportField(f.Name), e.exprString(f.Value))
	}
	// For built-in Result variants, include generic type args when the current
	// function has a known Result return type (populated by emitFnDecl) or when
	// the IIFE wrapper sets them. This is required for Go 1.18+ generics.
	name := rl.Name
	if e.resultTypeParams != "" {
		switch rl.Name {
		case builtinResultOk, builtinResultErr:
			name = fmt.Sprintf("%s[%s]", rl.Name, e.resultTypeParams)
		}
	}
	return fmt.Sprintf("%s{%s}", name, strings.Join(fields, ", "))
}

// identName returns the identifier name if expr is an *ast.Ident, otherwise "".
func identName(expr ast.Expr) string {
	if ident, ok := expr.(*ast.Ident); ok {
		return ident.Name
	}
	return ""
}

func (e *emitter) blockExpr(be *ast.BlockExpr) string {
	if len(be.Stmts) == 1 {
		return e.exprString(be.Stmts[0])
	}
	// Multi-statement blocks in expression position use an IIFE.
	var b strings.Builder
	b.WriteString("func() any {\n")
	for i, stmt := range be.Stmts {
		if i == len(be.Stmts)-1 {
			fmt.Fprintf(&b, "return %s\n", e.exprString(stmt))
		} else {
			fmt.Fprintf(&b, "%s\n", e.exprString(stmt))
		}
	}
	b.WriteString("}()")
	return b.String()
}

func (e *emitter) ifExprIIFE(ie *ast.IfExpr) string {
	goType := e.inferGoType(ie)
	var b strings.Builder
	fmt.Fprintf(&b, "func() %s {\n", goType)
	b.WriteString("if ")
	b.WriteString(e.exprString(ie.Cond))
	b.WriteString(" {\n")
	for _, stmt := range ie.Then[:len(ie.Then)-1] {
		fmt.Fprintf(&b, "%s\n", e.exprString(stmt))
	}
	if len(ie.Then) > 0 {
		fmt.Fprintf(&b, "return %s\n", e.exprString(ie.Then[len(ie.Then)-1]))
	}
	b.WriteString("}")
	if len(ie.Else) > 0 {
		b.WriteString(" else {\n")
		for _, stmt := range ie.Else[:len(ie.Else)-1] {
			fmt.Fprintf(&b, "%s\n", e.exprString(stmt))
		}
		fmt.Fprintf(&b, "return %s\n", e.exprString(ie.Else[len(ie.Else)-1]))
		b.WriteString("}")
	}
	b.WriteString("\n}()")
	return b.String()
}

// isConstructorMatch returns true if the match has constructor patterns (sum type matching).
func isConstructorMatch(me *ast.MatchExpr) bool {
	for _, arm := range me.Arms {
		if _, ok := arm.Pattern.(*ast.ConstructorPattern); ok {
			return true
		}
	}
	return false
}

// armGroup represents a group of match arms sharing the same outer constructor.
type armGroup struct {
	constructor string
	arms        []*ast.MatchArm
	isDefault   bool
}

// groupArmsByConstructor groups match arms by their outer constructor name.
// Wildcard/var patterns are placed in a single default group.
func groupArmsByConstructor(arms []*ast.MatchArm) []*armGroup {
	var groups []*armGroup
	idx := make(map[string]int)
	for _, arm := range arms {
		switch p := arm.Pattern.(type) {
		case *ast.ConstructorPattern:
			if i, ok := idx[p.Constructor]; ok {
				groups[i].arms = append(groups[i].arms, arm)
			} else {
				idx[p.Constructor] = len(groups)
				groups = append(groups, &armGroup{
					constructor: p.Constructor,
					arms:        []*ast.MatchArm{arm},
				})
			}
		default:
			groups = append(groups, &armGroup{
				arms:      []*ast.MatchArm{arm},
				isDefault: true,
			})
		}
	}
	return groups
}

// hasNestedConstructorPattern checks if any field in a constructor pattern
// has a nested constructor pattern.
func hasNestedConstructorPattern(cp *ast.ConstructorPattern) bool {
	for _, fp := range cp.Fields {
		if fp.Pattern != nil {
			if _, ok := fp.Pattern.(*ast.ConstructorPattern); ok {
				return true
			}
		}
	}
	return false
}

// findNestedFieldIdx returns the index of the first field with a nested
// constructor pattern in any of the given arms. Returns -1 if none found.
func findNestedFieldIdx(arms []*ast.MatchArm) int {
	for _, arm := range arms {
		cp, ok := arm.Pattern.(*ast.ConstructorPattern)
		if !ok {
			continue
		}
		for i, fp := range cp.Fields {
			if fp.Pattern != nil {
				if _, ok := fp.Pattern.(*ast.ConstructorPattern); ok {
					return i
				}
			}
		}
	}
	return -1
}

// emitMatchStmt emits a match expression in statement position.
func (e *emitter) emitMatchStmt(me *ast.MatchExpr) {
	if hasGuard(me) {
		e.emitGuardedMatchStmt(me)
		return
	}
	if isConstructorMatch(me) {
		e.emitTypeSwitchStmt(me)
	} else {
		e.emitValueSwitchStmt(me)
	}
}

func (e *emitter) emitTypeSwitchStmt(me *ast.MatchExpr) {
	scrutineeName := identName(me.Scrutinee)
	groups := groupArmsByConstructor(me.Arms)
	e.linef("switch __match := %s.(type) {", e.exprString(me.Scrutinee))
	for _, g := range groups {
		e.emitArmGroup(g, "__match", scrutineeName, 0, func(arm *ast.MatchArm) {
			e.emitBody(arm.Body)
		})
	}
	e.linef("}")
}

// emitArmGroup emits a single constructor group within a type switch.
// depth tracks nesting level for generating unique variable names.
//
//nolint:unparam // matchVar is always __match at top level but kept parameterized for nested switches
func (e *emitter) emitArmGroup(g *armGroup, matchVar, scrutineeName string, depth int, emitBody func(*ast.MatchArm)) {
	if g.isDefault {
		e.linef("default:")
		e.indent++
		arm := g.arms[0]
		if vp, ok := arm.Pattern.(*ast.VarPattern); ok {
			e.linef("%s := %s", vp.Name, matchVar)
		}
		emitBody(arm)
		e.indent--
		return
	}

	e.linef("case %s:", e.constructorCaseLabel(g.constructor, scrutineeName))
	e.indent++

	nestedIdx := findNestedFieldIdx(g.arms)
	if nestedIdx == -1 && len(g.arms) == 1 {
		// Simple case: single arm, no nested constructor patterns
		cp := g.arms[0].Pattern.(*ast.ConstructorPattern)
		e.emitPatternBindings(cp, matchVar)
		emitBody(g.arms[0])
		e.indent--
		return
	}

	if nestedIdx == -1 {
		// Multiple arms, same constructor, but no nesting — emit first arm
		cp := g.arms[0].Pattern.(*ast.ConstructorPattern)
		e.emitPatternBindings(cp, matchVar)
		emitBody(g.arms[0])
		e.indent--
		return
	}

	// Has nested constructor patterns — emit inner type switch
	cp0 := g.arms[0].Pattern.(*ast.ConstructorPattern)
	nestedFp := cp0.Fields[nestedIdx]
	fieldGoName := nestedFp.Name
	if nestedFp.OrigField != "" {
		fieldGoName = nestedFp.OrigField
	}

	nestVar := fmt.Sprintf("__nest_%d", depth)
	e.linef("switch %s := %s.%s.(type) {", nestVar, matchVar, exportField(fieldGoName))

	// Group inner patterns by their constructor
	innerGroups := e.groupInnerPatterns(g.arms, nestedIdx)
	for _, ig := range innerGroups {
		e.emitInnerGroup(ig, matchVar, nestVar, nestedIdx, depth, emitBody)
	}

	e.linef("}")
	e.indent--
}

// innerArmGroup represents a group of arms sharing the same inner constructor at a nested field.
type innerArmGroup struct {
	constructor string
	arms        []*ast.MatchArm
	innerCps    []*ast.ConstructorPattern // the inner constructor patterns
	isDefault   bool
}

// groupInnerPatterns groups arms by the inner pattern at the specified field index.
func (e *emitter) groupInnerPatterns(arms []*ast.MatchArm, fieldIdx int) []*innerArmGroup {
	var groups []*innerArmGroup
	idx := make(map[string]int)
	for _, arm := range arms {
		cp := arm.Pattern.(*ast.ConstructorPattern)
		fp := cp.Fields[fieldIdx]
		if fp.Pattern == nil {
			// Shorthand binding — treat as default (binds field to variable)
			groups = append(groups, &innerArmGroup{
				arms:      []*ast.MatchArm{arm},
				isDefault: true,
			})
			continue
		}
		switch inner := fp.Pattern.(type) {
		case *ast.ConstructorPattern:
			if i, ok := idx[inner.Constructor]; ok {
				groups[i].arms = append(groups[i].arms, arm)
				groups[i].innerCps = append(groups[i].innerCps, inner)
			} else {
				idx[inner.Constructor] = len(groups)
				groups = append(groups, &innerArmGroup{
					constructor: inner.Constructor,
					arms:        []*ast.MatchArm{arm},
					innerCps:    []*ast.ConstructorPattern{inner},
				})
			}
		case *ast.VarPattern, *ast.WildcardPattern:
			groups = append(groups, &innerArmGroup{
				arms:      []*ast.MatchArm{arm},
				isDefault: true,
			})
		}
	}
	return groups
}

// emitInnerGroup emits a case within a nested type switch.
func (e *emitter) emitInnerGroup(ig *innerArmGroup, outerVar, nestVar string, nestedFieldIdx, depth int, emitBody func(*ast.MatchArm)) {
	arm := ig.arms[0]
	cp := arm.Pattern.(*ast.ConstructorPattern)

	if ig.isDefault {
		e.linef("default:")
		e.indent++
		// Emit non-nested field bindings
		e.emitNonNestedBindings(cp, outerVar, nestedFieldIdx)
		// Handle the default inner binding
		fp := cp.Fields[nestedFieldIdx]
		if fp.Pattern == nil {
			e.linef("%s := %s", fp.Name, nestVar)
		} else if vp, ok := fp.Pattern.(*ast.VarPattern); ok {
			e.linef("%s := %s", vp.Name, nestVar)
		}
		emitBody(arm)
		e.indent--
		return
	}

	e.linef("case %s:", ig.constructor)
	e.indent++

	innerCp := ig.innerCps[0]
	// Check for deeper nesting
	if hasNestedConstructorPattern(innerCp) {
		// Emit non-nested field bindings from outer
		e.emitNonNestedBindings(cp, outerVar, nestedFieldIdx)
		// Recurse: create inner arm group
		innerGroup := &armGroup{
			constructor: ig.constructor,
			arms:        ig.arms,
		}
		// Transform arms to use inner patterns
		transformedArms := make([]*ast.MatchArm, len(ig.arms))
		for i, a := range ig.arms {
			transformedArms[i] = &ast.MatchArm{
				Span:    a.Span,
				Pattern: ig.innerCps[i],
				Guard:   a.Guard,
				Body:    a.Body,
			}
		}
		innerGroup.arms = transformedArms
		nestedIdx2 := findNestedFieldIdx(transformedArms)
		if nestedIdx2 != -1 {
			// Deeper nesting — recurse via a new arm group
			ig2 := &armGroup{
				constructor: ig.constructor,
				arms:        transformedArms,
			}
			// Re-emit as nested
			e.emitNestedBody(ig2, nestVar, depth+1, emitBody)
		} else {
			e.emitPatternBindings(innerCp, nestVar)
			emitBody(arm)
		}
	} else {
		// Emit non-nested field bindings from outer
		e.emitNonNestedBindings(cp, outerVar, nestedFieldIdx)
		// Emit inner field bindings
		e.emitPatternBindings(innerCp, nestVar)
		emitBody(arm)
	}

	e.indent--
}

// emitNestedBody handles the body of a constructor group that has nested patterns.
// It emits the inner type switch for the nested field.
func (e *emitter) emitNestedBody(g *armGroup, matchVar string, depth int, emitBody func(*ast.MatchArm)) {
	nestedIdx := findNestedFieldIdx(g.arms)
	if nestedIdx == -1 {
		// No more nesting
		cp := g.arms[0].Pattern.(*ast.ConstructorPattern)
		e.emitPatternBindings(cp, matchVar)
		emitBody(g.arms[0])
		return
	}

	cp0 := g.arms[0].Pattern.(*ast.ConstructorPattern)
	nestedFp := cp0.Fields[nestedIdx]
	fieldGoName := nestedFp.Name
	if nestedFp.OrigField != "" {
		fieldGoName = nestedFp.OrigField
	}

	nestVar := fmt.Sprintf("__nest_%d", depth)
	e.linef("switch %s := %s.%s.(type) {", nestVar, matchVar, exportField(fieldGoName))

	innerGroups := e.groupInnerPatterns(g.arms, nestedIdx)
	for _, ig := range innerGroups {
		e.emitInnerGroup(ig, matchVar, nestVar, nestedIdx, depth, emitBody)
	}

	e.linef("}")
}

// emitNonNestedBindings emits field bindings for all fields except the nested one.
func (e *emitter) emitNonNestedBindings(cp *ast.ConstructorPattern, varName string, skipIdx int) {
	for i, fp := range cp.Fields {
		if i == skipIdx {
			continue
		}
		e.emitSingleFieldBinding(fp, varName)
	}
}

// emitSingleFieldBinding emits a single field binding, handling var/wildcard patterns.
func (e *emitter) emitSingleFieldBinding(fp *ast.FieldPattern, varName string) {
	fieldName := fp.Name
	if fp.OrigField != "" {
		fieldName = fp.OrigField
	}
	if fp.Pattern == nil {
		e.linef("%s := %s.%s", fp.Name, varName, exportField(fieldName))
	} else if vp, ok := fp.Pattern.(*ast.VarPattern); ok {
		e.linef("%s := %s.%s", vp.Name, varName, exportField(fieldName))
	}
	// WildcardPattern: no binding needed
}

func (e *emitter) emitValueSwitchStmt(me *ast.MatchExpr) {
	e.emitValueSwitch(me, func(arm *ast.MatchArm) {
		e.emitBody(arm.Body)
	})
}

// emitValueSwitch emits a Go `switch scrut { ... }` over literal arms,
// dispatching each arm body through the emitBody callback. Var/wildcard
// arms become the default case.
func (e *emitter) emitValueSwitch(me *ast.MatchExpr, emitBody func(*ast.MatchArm)) {
	e.linef("switch %s {", e.exprString(me.Scrutinee))
	for _, arm := range me.Arms {
		switch p := arm.Pattern.(type) {
		case *ast.LiteralPattern:
			e.linef("case %s:", e.exprString(p.Value))
			e.indent++
			emitBody(arm)
			e.indent--
		case *ast.VarPattern:
			e.linef("default:")
			e.indent++
			e.linef("%s := %s", p.Name, e.exprString(me.Scrutinee))
			emitBody(arm)
			e.indent--
		case *ast.WildcardPattern:
			e.linef("default:")
			e.indent++
			emitBody(arm)
			e.indent--
		}
	}
	e.linef("}")
}

func (e *emitter) emitPatternBindings(p *ast.ConstructorPattern, varName string) {
	for _, fp := range p.Fields {
		e.emitSingleFieldBinding(fp, varName)
	}
}

// constructorCaseLabel returns the Go type switch case label for a constructor,
// adding generic type arguments when the scrutinee was produced by a GoLiftCallExpr.
func (e *emitter) constructorCaseLabel(constructor, scrutineeName string) string {
	if e.liftedVars == nil {
		return constructor
	}
	vt, ok := e.liftedVars[scrutineeName]
	if !ok {
		return constructor
	}
	errType := "error"
	valueType := vt
	if valueType == "" {
		valueType = "struct{}"
	}
	return fmt.Sprintf("%s[%s, %s]", constructor, valueType, errType)
}

// emitMatchAssign emits a match expression as a result variable assignment.
func (e *emitter) emitMatchAssign(name string, me *ast.MatchExpr) {
	goType := e.inferMatchType(me)
	e.linef("var %s %s", name, goType)
	if hasGuard(me) {
		e.emitGuardedMatchAssign(name, me)
		return
	}
	if isConstructorMatch(me) {
		e.emitTypeSwitchAssign(name, me)
	} else {
		e.emitValueSwitchAssign(name, me)
	}
}

func (e *emitter) emitTypeSwitchAssign(name string, me *ast.MatchExpr) {
	scrutineeName := identName(me.Scrutinee)
	groups := groupArmsByConstructor(me.Arms)
	e.linef("switch __match := %s.(type) {", e.exprString(me.Scrutinee))
	for _, g := range groups {
		e.emitArmGroup(g, "__match", scrutineeName, 0, func(arm *ast.MatchArm) {
			e.emitMatchArmAssign(name, arm.Body)
		})
	}
	e.linef("}")
}

func (e *emitter) emitValueSwitchAssign(name string, me *ast.MatchExpr) {
	e.emitValueSwitch(me, func(arm *ast.MatchArm) {
		e.emitMatchArmAssign(name, arm.Body)
	})
}

func (e *emitter) emitMatchArmAssign(name string, body []ast.Expr) {
	last := e.emitArmLead(body)
	if last == nil {
		return
	}
	// If the last statement is a return, emit it as a statement rather than an assignment.
	if _, isReturn := last.(*ast.ReturnExpr); isReturn {
		e.emitStmt(last)
		return
	}
	e.linef("%s = %s", name, e.exprString(last))
}

func (e *emitter) matchExprIIFE(me *ast.MatchExpr) string {
	goType := e.inferMatchType(me)

	// Temporarily redirect emitter output to capture IIFE body.
	savedBuf := e.buf
	savedIndent := e.indent
	e.buf = strings.Builder{}
	e.indent = 0

	switch {
	case hasGuard(me):
		e.emitGuardedMatchIIFEBody(me)
	case isConstructorMatch(me):
		e.emitTypeSwitchIIFEBody(me)
	default:
		e.emitValueSwitchIIFEBody(me)
	}

	body := e.buf.String()
	e.buf = savedBuf
	e.indent = savedIndent

	var b strings.Builder
	fmt.Fprintf(&b, "func() %s {\n%sreturn *new(%s)\n}()", goType, body, goType)
	return b.String()
}

func (e *emitter) emitTypeSwitchIIFEBody(me *ast.MatchExpr) {
	scrutineeName := identName(me.Scrutinee)
	groups := groupArmsByConstructor(me.Arms)
	e.linef("switch __match := %s.(type) {", e.exprString(me.Scrutinee))
	for _, g := range groups {
		e.emitArmGroup(g, "__match", scrutineeName, 0, func(arm *ast.MatchArm) {
			e.emitReturnBody(arm.Body)
		})
	}
	e.linef("}")
}

func (e *emitter) emitValueSwitchIIFEBody(me *ast.MatchExpr) {
	e.emitValueSwitch(me, func(arm *ast.MatchArm) {
		e.emitReturnBody(arm.Body)
	})
}

// emitReturnBody emits the body of a match arm as return statements for IIFE context.
func (e *emitter) emitReturnBody(body []ast.Expr) {
	if len(body) == 0 {
		return
	}
	for _, stmt := range body[:len(body)-1] {
		e.linef("%s", e.exprString(stmt))
	}
	e.linef("return %s", e.exprString(body[len(body)-1]))
}

// --- Guarded match emission ---
//
// When a match contains any arm with a guard clause, we cannot use a Go
// switch because the guard may filter out a matched value and we need to
// try the next arm. Instead we emit a for-loop with a sequential if-chain:
// each arm is a type assertion (or value compare) that opens a scope for
// bindings, runs the guard, executes the body, and breaks out of the loop.

// hasGuard reports whether any arm of a match has a guard clause.
func hasGuard(me *ast.MatchExpr) bool {
	for _, arm := range me.Arms {
		if arm.Guard != nil {
			return true
		}
	}
	return false
}

// guardedScrutineeName returns the Go identifier used to refer to the
// scrutinee inside a guarded match body. If the scrutinee is already an
// ident, its name is used directly; otherwise a __scrut temporary is
// emitted and its name returned.
func (e *emitter) guardedScrutineeName(me *ast.MatchExpr) string {
	if name := identName(me.Scrutinee); name != "" {
		return name
	}
	e.linef("__scrut := %s", e.exprString(me.Scrutinee))
	return "__scrut"
}

// emitGuardedMatchReturn emits a guarded match in tail-return position.
func (e *emitter) emitGuardedMatchReturn(me *ast.MatchExpr) {
	scrut := e.guardedScrutineeName(me)
	e.linef("for {")
	e.indent++
	for _, arm := range me.Arms {
		e.emitGuardedArm(arm, scrut, func(a *ast.MatchArm) {
			e.emitMatchArmReturn(a.Body)
		})
	}
	e.linef("break")
	e.indent--
	e.linef("}")
	e.linef(`panic("unreachable")`)
}

// emitGuardedMatchStmt emits a guarded match in statement position.
func (e *emitter) emitGuardedMatchStmt(me *ast.MatchExpr) {
	scrut := e.guardedScrutineeName(me)
	e.linef("for {")
	e.indent++
	for _, arm := range me.Arms {
		e.emitGuardedArm(arm, scrut, func(a *ast.MatchArm) {
			e.emitGuardedArmStmtBody(a.Body)
		})
	}
	e.linef("break")
	e.indent--
	e.linef("}")
}

// emitGuardedMatchAssign emits a guarded match that assigns its result to name.
func (e *emitter) emitGuardedMatchAssign(name string, me *ast.MatchExpr) {
	scrut := e.guardedScrutineeName(me)
	e.linef("for {")
	e.indent++
	for _, arm := range me.Arms {
		e.emitGuardedArm(arm, scrut, func(a *ast.MatchArm) {
			e.emitGuardedArmAssignBody(name, a.Body)
		})
	}
	e.linef("break")
	e.indent--
	e.linef("}")
}

// emitGuardedMatchIIFEBody emits a guarded match as the body of a func() T IIFE.
func (e *emitter) emitGuardedMatchIIFEBody(me *ast.MatchExpr) {
	scrut := e.guardedScrutineeName(me)
	e.linef("for {")
	e.indent++
	for _, arm := range me.Arms {
		e.emitGuardedArm(arm, scrut, func(a *ast.MatchArm) {
			e.emitReturnBody(a.Body)
		})
	}
	e.linef("break")
	e.indent--
	e.linef("}")
	e.linef(`panic("unreachable")`)
}

// emitGuardedArm emits a single arm within the for-loop: a conditional scope
// containing bindings, optional guard, and the body.
func (e *emitter) emitGuardedArm(arm *ast.MatchArm, scrut string, emitBody func(*ast.MatchArm)) {
	switch p := arm.Pattern.(type) {
	case *ast.ConstructorPattern:
		label := e.constructorCaseLabel(p.Constructor, scrut)
		e.linef("if __v, __ok := %s.(%s); __ok {", scrut, label)
		e.indent++
		e.emitPatternBindings(p, "__v")
		e.emitGuardedBody(arm, emitBody)
		e.indent--
		e.linef("}")
	case *ast.LiteralPattern:
		e.linef("if %s == %s {", scrut, e.exprString(p.Value))
		e.indent++
		e.emitGuardedBody(arm, emitBody)
		e.indent--
		e.linef("}")
	case *ast.VarPattern:
		e.linef("{")
		e.indent++
		e.linef("%s := %s", p.Name, scrut)
		e.emitGuardedBody(arm, emitBody)
		e.indent--
		e.linef("}")
	case *ast.WildcardPattern:
		e.linef("{")
		e.indent++
		e.emitGuardedBody(arm, emitBody)
		e.indent--
		e.linef("}")
	}
}

// emitGuardedBody wraps the body in the arm's guard condition when present.
func (e *emitter) emitGuardedBody(arm *ast.MatchArm, emitBody func(*ast.MatchArm)) {
	if arm.Guard == nil {
		emitBody(arm)
		return
	}
	e.linef("if %s {", e.exprString(arm.Guard))
	e.indent++
	emitBody(arm)
	e.indent--
	e.linef("}")
}

// emitGuardedArmStmtBody emits an arm body in statement context, then breaks.
// A trailing return in the body replaces the break because it already exits.
func (e *emitter) emitGuardedArmStmtBody(body []ast.Expr) {
	last := e.emitArmLead(body)
	if last == nil {
		e.linef("break")
		return
	}
	e.emitStmt(last)
	if _, isReturn := last.(*ast.ReturnExpr); !isReturn {
		e.linef("break")
	}
}

// emitGuardedArmAssignBody emits an arm body that assigns its value to name,
// then breaks. A trailing return in the body replaces the assign+break.
func (e *emitter) emitGuardedArmAssignBody(name string, body []ast.Expr) {
	last := e.emitArmLead(body)
	if last == nil {
		e.linef("break")
		return
	}
	if _, isReturn := last.(*ast.ReturnExpr); isReturn {
		e.emitStmt(last)
		return
	}
	e.linef("%s = %s", name, e.exprString(last))
	e.linef("break")
}

func (e *emitter) inferMatchType(me *ast.MatchExpr) string {
	if len(me.Arms) == 0 {
		return goAny
	}
	arm := me.Arms[0]
	if len(arm.Body) == 0 {
		return goAny
	}
	return e.inferExprType(arm.Body[len(arm.Body)-1])
}

func (e *emitter) fnLit(fl *ast.FnLit) string {
	params := e.paramList(fl.Params)
	ret := ""
	if fl.ReturnType != nil {
		ret = " " + e.typeExpr(fl.ReturnType)
	}
	var b strings.Builder
	fmt.Fprintf(&b, "func(%s)%s {\n", params, ret)
	for _, stmt := range fl.Body {
		fmt.Fprintf(&b, "%s\n", e.exprString(stmt))
	}
	b.WriteString("}")
	return b.String()
}

func (e *emitter) typeExpr(te ast.TypeExpr) string {
	if te == nil {
		return ""
	}
	switch t := te.(type) {
	case *ast.NamedType:
		return goTypeName(t.Name)
	case *ast.QualifiedType:
		return t.Qualifier + "." + t.Name
	case *ast.PointerType:
		return "*" + e.typeExpr(t.Elem)
	case *ast.FnType:
		params := make([]string, len(t.ParamTypes))
		for i, p := range t.ParamTypes {
			params[i] = e.typeExpr(p)
		}
		ret := ""
		if t.ReturnType != nil {
			ret = " " + e.typeExpr(t.ReturnType)
		}
		return fmt.Sprintf("func(%s)%s", strings.Join(params, ", "), ret)
	case *ast.GenericType:
		args := make([]string, len(t.TypeArgs))
		for i, a := range t.TypeArgs {
			args[i] = e.typeExpr(a)
		}
		return fmt.Sprintf("%s[%s]", goTypeName(t.Name), strings.Join(args, ", "))
	default:
		return goAny
	}
}

// emitBuiltinTypes emits Go type definitions for built-in types (Result, Option)
// only if they are referenced in the module's declarations.
func (e *emitter) emitBuiltinTypes(decls []ast.Decl) {
	needsResult, needsOption := scanForBuiltins(decls)

	if needsOption {
		e.buf.WriteByte('\n')
		e.emitSumTypeDecl("Option", []string{"T"}, &ast.SumTypeBody{
			Variants: []*ast.Variant{
				{Name: "OptionSome", Fields: []*ast.FieldDef{{Name: "value", Type: &ast.NamedType{Name: "T"}}}},
				{Name: "OptionNone", Fields: nil},
			},
		})
		e.buf.WriteByte('\n')
	}

	if needsResult {
		e.buf.WriteByte('\n')
		e.emitSumTypeDecl("Result", []string{"T", "E"}, &ast.SumTypeBody{
			Variants: []*ast.Variant{
				{Name: "ResultOk", Fields: []*ast.FieldDef{{Name: "value", Type: &ast.NamedType{Name: "T"}}}},
				{Name: "ResultErr", Fields: []*ast.FieldDef{{Name: "error", Type: &ast.NamedType{Name: "E"}}}},
			},
		})
		e.buf.WriteByte('\n')
	}
}

// scanForBuiltins checks if Result or Option variant names appear in the declarations.
func scanForBuiltins(decls []ast.Decl) (needsResult, needsOption bool) {
	for _, decl := range decls {
		scanExprForBuiltins(declExprs(decl), &needsResult, &needsOption)
		if needsResult && needsOption {
			return
		}
	}
	return
}

func declExprs(decl ast.Decl) []ast.Expr {
	switch d := decl.(type) {
	case *ast.FnDecl:
		return d.Body
	case *ast.LetDecl:
		return []ast.Expr{d.Value}
	default:
		return nil
	}
}

func scanExprForBuiltins(exprs []ast.Expr, needsResult, needsOption *bool) {
	for _, expr := range exprs {
		scanExpr(expr, needsResult, needsOption)
	}
}

//nolint:funlen,cyclop // scanning all expression kinds
func scanExpr(expr ast.Expr, needsResult, needsOption *bool) {
	if expr == nil {
		return
	}
	switch e := expr.(type) {
	case *ast.Ident:
		switch e.Name {
		case builtinResultOk, builtinResultErr:
			*needsResult = true
		case builtinOptionSome, builtinOptionNone:
			*needsOption = true
		}
	case *ast.RecordLit:
		switch e.Name {
		case builtinResultOk, builtinResultErr:
			*needsResult = true
		case builtinOptionSome, builtinOptionNone:
			*needsOption = true
		}
		for _, f := range e.Fields {
			scanExpr(f.Value, needsResult, needsOption)
		}
	case *ast.BinaryExpr:
		scanExpr(e.Left, needsResult, needsOption)
		scanExpr(e.Right, needsResult, needsOption)
	case *ast.UnaryExpr:
		scanExpr(e.Operand, needsResult, needsOption)
	case *ast.CallExpr:
		scanExpr(e.Func, needsResult, needsOption)
		scanExprForBuiltins(e.Args, needsResult, needsOption)
	case *ast.FieldAccessExpr:
		scanExpr(e.Expr, needsResult, needsOption)
	case *ast.BlockExpr:
		scanExprForBuiltins(e.Stmts, needsResult, needsOption)
	case *ast.IfExpr:
		scanExpr(e.Cond, needsResult, needsOption)
		scanExprForBuiltins(e.Then, needsResult, needsOption)
		scanExprForBuiltins(e.Else, needsResult, needsOption)
	case *ast.LetExpr:
		scanExpr(e.Value, needsResult, needsOption)
	case *ast.ReturnExpr:
		scanExpr(e.Value, needsResult, needsOption)
	case *ast.MatchExpr:
		scanExpr(e.Scrutinee, needsResult, needsOption)
		for _, arm := range e.Arms {
			scanPattern(arm.Pattern, needsResult, needsOption)
			scanExprForBuiltins(arm.Body, needsResult, needsOption)
		}
	case *ast.FnLit:
		scanExprForBuiltins(e.Body, needsResult, needsOption)
	case *ast.GoLiftCallExpr:
		// GoLiftCallExpr always wraps its result in Result[...], so Result builtins are needed.
		*needsResult = true
		scanExpr(e.Call, needsResult, needsOption)
	}
}

func scanPattern(pat ast.Pattern, needsResult, needsOption *bool) {
	if cp, ok := pat.(*ast.ConstructorPattern); ok {
		switch cp.Constructor {
		case builtinResultOk, builtinResultErr:
			*needsResult = true
		case builtinOptionSome, builtinOptionNone:
			*needsOption = true
		}
	}
}

// goTypeParamDecl builds a Go type parameter declaration string, e.g. "[T any, E any]".
// Returns "" if there are no type params.
func goTypeParamDecl(typeParams []string) string {
	if len(typeParams) == 0 {
		return ""
	}
	parts := make([]string, len(typeParams))
	for i, tp := range typeParams {
		parts[i] = tp + " any"
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

// goTypeParamUse builds a Go type parameter usage string, e.g. "[T, E]".
// Returns "" if there are no type params.
func goTypeParamUse(typeParams []string) string {
	if len(typeParams) == 0 {
		return ""
	}
	return "[" + strings.Join(typeParams, ", ") + "]"
}

// goTypeName maps Golem built-in type names to Go type names.
func goTypeName(name string) string {
	switch name {
	case "Int":
		return goInt
	case "Float":
		return goFloat64
	case "String":
		return goString
	case "Bool":
		return goBool
	case "Any":
		return goAny
	case "Error":
		return "error"
	default:
		return name
	}
}

// goOperator maps a Golem binary operator to its Go equivalent.
func goOperator(op ast.BinaryOp) string {
	switch op {
	case ast.OpAdd:
		return "+"
	case ast.OpSub:
		return "-"
	case ast.OpMul:
		return "*"
	case ast.OpDiv:
		return "/"
	case ast.OpMod:
		return "%"
	case ast.OpEq:
		return "=="
	case ast.OpNeq:
		return "!="
	case ast.OpLt:
		return "<"
	case ast.OpGt:
		return ">"
	case ast.OpLte:
		return "<="
	case ast.OpGte:
		return ">="
	case ast.OpAnd:
		return "&&"
	case ast.OpOr:
		return "||"
	case ast.OpConcat:
		return "+"
	default:
		return "?"
	}
}

// exportField capitalizes the first letter of a field name for Go export.
func exportField(name string) string {
	if len(name) == 0 {
		return name
	}
	runes := []rune(name)
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

func sortedImports(imports map[string]bool) []string {
	paths := make([]string, 0, len(imports))
	for p := range imports {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	return paths
}
