package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/dylanblakemore/golem/internal/goloader"
)

func TestDiscoverGolemFiles(t *testing.T) {
	dir := t.TempDir()

	// Create .golem files and non-.golem files.
	writeFile(t, filepath.Join(dir, "main.golem"), "pub fn main() do\n  42\nend")
	writeFile(t, filepath.Join(dir, "lib.golem"), "fn helper() do\n  1\nend")
	writeFile(t, filepath.Join(dir, "readme.md"), "# readme")

	// Create a nested directory with a .golem file.
	sub := filepath.Join(dir, "sub")
	mkDir(t, sub)
	writeFile(t, filepath.Join(sub, "nested.golem"), "fn nested() do\n  2\nend")

	// Create a build directory that should be skipped.
	buildDir := filepath.Join(dir, "build")
	mkDir(t, buildDir)
	writeFile(t, filepath.Join(buildDir, "skip.golem"), "fn skip() do\n  0\nend")

	files, err := discoverGolemFiles(dir)
	if err != nil {
		t.Fatalf("discoverGolemFiles error: %v", err)
	}

	// Should find 3 files (main, lib, nested) but not readme or build/skip.
	if len(files) != 3 {
		t.Errorf("expected 3 .golem files, got %d: %v", len(files), files)
	}
	for _, f := range files {
		if strings.Contains(f, "readme") {
			t.Error("should not discover non-.golem files")
		}
		if strings.Contains(f, "build") {
			t.Error("should not discover files in build/ directory")
		}
	}
}

func TestGolemOutputPath(t *testing.T) {
	tests := []struct {
		input string
		want  string
	}{
		{"main.golem", filepath.Join("build", "main.golem.go")},
		{"src/lib.golem", filepath.Join("build", "src", "lib.golem.go")},
	}
	for _, tt := range tests {
		got := golemOutputPath(tt.input)
		if got != tt.want {
			t.Errorf("golemOutputPath(%q) = %q, want %q", tt.input, got, tt.want)
		}
	}
}

func TestCompileFileSuccess(t *testing.T) {
	dir := t.TempDir()
	origDir := chDir(t, dir)
	defer restoreDir(t, origDir)

	writeFile(t, filepath.Join(dir, "hello.golem"), `import "fmt"

pub fn main() do
  fmt.println("hello")
end`)

	mkDir(t, filepath.Join(dir, "build"))

	ok := compileFile("hello.golem", false, goloader.New())
	if !ok {
		t.Fatal("compileFile failed")
	}

	outPath := filepath.Join(dir, "build", "hello.golem.go")
	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("could not read output: %v", err)
	}
	out := string(data)

	if !strings.Contains(out, "package main") {
		t.Error("output should contain package main")
	}
	if !strings.Contains(out, "// Code generated by golem. DO NOT EDIT.") {
		t.Error("output should contain generated header")
	}
	if !strings.Contains(out, `fmt.Println("hello")`) {
		t.Error("output should contain fmt.Println call")
	}
	if !strings.HasSuffix(outPath, ".golem.go") {
		t.Error("output file should have .golem.go extension")
	}
}

func TestCompileFileParseError(t *testing.T) {
	dir := t.TempDir()
	origDir := chDir(t, dir)
	defer restoreDir(t, origDir)

	writeFile(t, filepath.Join(dir, "bad.golem"), "fn bad( do\nend")
	mkDir(t, filepath.Join(dir, "build"))

	ok := compileFile("bad.golem", false, goloader.New())
	if ok {
		t.Error("compileFile should fail on parse error")
	}
}

func TestCompileFileTypeError(t *testing.T) {
	dir := t.TempDir()
	origDir := chDir(t, dir)
	defer restoreDir(t, origDir)

	writeFile(t, filepath.Join(dir, "typeerr.golem"), `pub fn main(): Int do
  "not an int" + 1
end`)
	mkDir(t, filepath.Join(dir, "build"))

	ok := compileFile("typeerr.golem", false, goloader.New())
	if ok {
		t.Error("compileFile should fail on type error")
	}
}

func TestCompileFileVerbose(t *testing.T) {
	dir := t.TempDir()
	origDir := chDir(t, dir)
	defer restoreDir(t, origDir)

	writeFile(t, filepath.Join(dir, "hello.golem"), `pub fn main() do
  42
end`)
	mkDir(t, filepath.Join(dir, "build"))

	// Just ensure verbose mode doesn't crash.
	ok := compileFile("hello.golem", true, goloader.New())
	if !ok {
		t.Fatal("compileFile with verbose should succeed")
	}
}

func TestHTTPServerEndToEnd(t *testing.T) {
	dir := t.TempDir()
	origDir := chDir(t, dir)
	defer restoreDir(t, origDir)

	writeFile(t, filepath.Join(dir, "server.golem"), `import "net/http"
import "fmt"

pub fn main() do
  http.handleFunc("/", fn(w: http.ResponseWriter, r: *http.Request) do
    fmt.fprintln(w, "Hello from Golem!")
  end)
  fmt.println("Listening on :8080")
  http.listenAndServe(":8080", nil)
end`)

	mkDir(t, filepath.Join(dir, "build"))

	ok := compileFile("server.golem", false, goloader.New())
	if !ok {
		t.Fatal("HTTP server example failed to compile")
	}

	outPath := filepath.Join(dir, "build", "server.golem.go")
	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("could not read output: %v", err)
	}
	out := string(data)

	// Verify generated code is readable and idiomatic.
	assertContains(t, out, "package main")
	assertContains(t, out, "// Code generated by golem. DO NOT EDIT.")
	assertContains(t, out, `"net/http"`)
	assertContains(t, out, `"fmt"`)
	assertContains(t, out, "func main()")
	assertContains(t, out, "http.HandleFunc")
	assertContains(t, out, "func(w http.ResponseWriter, r *http.Request)")
	assertContains(t, out, `fmt.Fprintln(w, "Hello from Golem!")`)
	assertContains(t, out, `fmt.Println("Listening on :8080")`)
	assertContains(t, out, `http.ListenAndServe(":8080", nil)`)

	// Verify the generated code compiles as valid Go.
	goMod := filepath.Join(dir, "build", "go.mod")
	writeFile(t, goMod, "module golem-test\n\ngo 1.21\n")
	goVet := exec.Command("go", "vet", "./...")
	goVet.Dir = filepath.Join(dir, "build")
	if vetOut, err := goVet.CombinedOutput(); err != nil {
		t.Fatalf("go vet failed on generated code: %v\n%s", err, vetOut)
	}
	goBuild := exec.Command("go", "build", "-o", os.DevNull, ".")
	goBuild.Dir = filepath.Join(dir, "build")
	if buildOut, err := goBuild.CombinedOutput(); err != nil {
		t.Fatalf("go build failed on generated code: %v\n%s", err, buildOut)
	}
}

func TestADTDomainModelEndToEnd(t *testing.T) {
	dir := t.TempDir()
	origDir := chDir(t, dir)
	defer restoreDir(t, origDir)

	writeFile(t, filepath.Join(dir, "domain.golem"), `import "os"
import "fmt"

type FileResult =
  | TextFile { content: String }
  | EmptyFile
  | ReadError { message: String }

priv fn describeResult(r: FileResult): String do
  match r do
    | TextFile { content } -> "Got content: " <> content
    | EmptyFile -> "File was empty"
    | ReadError { message } -> "Error: " <> message
  end
end

pub fn processFile(path: String): String do
  let result = os.readFile(path)
  match result do
    | Ok { value } -> describeResult(TextFile { content: fmt.sprintf("%s", value) })
    | Err { error } -> describeResult(ReadError { message: fmt.sprintf("%v", error) })
  end
end

pub fn main() do
  fmt.println(processFile("/etc/hosts"))
end`)

	mkDir(t, filepath.Join(dir, "build"))

	ok := compileFile("domain.golem", false, goloader.New())
	if !ok {
		t.Fatal("ADT domain model example failed to compile")
	}

	outPath := filepath.Join(dir, "build", "domain.golem.go")
	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("could not read output: %v", err)
	}
	out := string(data)

	// Sum type variants generate correctly (type is unqualified, so lowercase in Go).
	assertContains(t, out, "type fileResult interface")
	assertContains(t, out, "type fileResultTextFile struct")
	assertContains(t, out, "type fileResultEmptyFile struct")
	assertContains(t, out, "type fileResultReadError struct")

	// Pattern matching is present.
	assertContains(t, out, "func describeResult(")
	assertContains(t, out, "func ProcessFile(")

	// Go interop types map correctly (Result IIFE wrapper for os.ReadFile).
	assertContains(t, out, "func() Result[[]byte, error]")
	assertContains(t, out, "os.ReadFile(")

	// Type switch cases use concrete type parameters.
	assertContains(t, out, "case ResultOk[[]byte, error]:")
	assertContains(t, out, "case ResultErr[[]byte, error]:")

	// fmt import is present.
	assertContains(t, out, `"fmt"`)
	assertContains(t, out, `"os"`)

	// Verify the generated code compiles as valid Go.
	goMod := filepath.Join(dir, "build", "go.mod")
	writeFile(t, goMod, "module golem-test\n\ngo 1.21\n")
	goVet := exec.Command("go", "vet", "./...")
	goVet.Dir = filepath.Join(dir, "build")
	if vetOut, err := goVet.CombinedOutput(); err != nil {
		t.Fatalf("go vet failed on generated code: %v\n%s\nGenerated:\n%s", err, vetOut, out)
	}
	goBuild := exec.Command("go", "build", "-o", os.DevNull, ".")
	goBuild.Dir = filepath.Join(dir, "build")
	if buildOut, err := goBuild.CombinedOutput(); err != nil {
		t.Fatalf("go build failed on generated code: %v\n%s\nGenerated:\n%s", err, buildOut, out)
	}
}

func assertContains(t *testing.T, haystack, needle string) {
	t.Helper()
	if !strings.Contains(haystack, needle) {
		t.Errorf("output should contain %q", needle)
	}
}

// Helpers.

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatalf("writeFile: %v", err)
	}
}

func mkDir(t *testing.T, path string) {
	t.Helper()
	if err := os.MkdirAll(path, dirPerm); err != nil {
		t.Fatalf("mkDir: %v", err)
	}
}

func chDir(t *testing.T, dir string) string {
	t.Helper()
	orig, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	if err := os.Chdir(dir); err != nil {
		t.Fatalf("chdir: %v", err)
	}
	return orig
}

func restoreDir(t *testing.T, dir string) {
	t.Helper()
	if err := os.Chdir(dir); err != nil {
		t.Fatalf("restore chdir: %v", err)
	}
}
